# Generated by Django 5.0 on 2026-03-09 00:00
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=64)),
                ('vendor_name', models.CharField(max_length=255)),
                ('tech_type', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('Pre-Qualification', 'Pre-Qualification'), ('Site-Specific Proposal', 'Site-Specific Proposal'), ('Contracting', 'Contracting'), ('Installation', 'Installation'), ('Field Verification', 'Field Verification'), ('Disbursement', 'Disbursement'), ('Completed', 'Completed')], max_length=32)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('energy_output', models.FloatField(default=0.0)),
                ('uptime', models.FloatField(default=0.0)),
                ('gender_impact', models.FloatField(default=0.0)),
            ],
        ),
    ]
