# Generated by Django 5.0.6 on 2026-03-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Pre-Qualification', 'Pre Qualification'), ('Site-Specific Proposal', 'Site Specific'), ('Contracting', 'Contracting'), ('Installation', 'Installation'), ('Field Verification', 'Verification'), ('Disbursement', 'Disbursement'), ('Completed', 'Completed')], max_length=32),
        ),
    ]
