# Generated by Django 5.0.6 on 2026-04-30 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_generated_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('finding_category', models.CharField(choices=[('payment_compliance', 'Payment Compliance'), ('approval_chain_violation', 'Approval Chain Violation'), ('data_integrity', 'Data Integrity'), ('gps_fraud', 'GPS / Location Fraud'), ('kpi_manipulation', 'KPI Manipulation'), ('document_irregularity', 'Document Irregularity'), ('process_violation', 'Process Violation'), ('conflict_of_interest', 'Conflict of Interest'), ('other', 'Other Compliance Issue')], max_length=32)),
                ('risk_level', models.CharField(choices=[('observation', 'Observation'), ('minor', 'Minor Finding'), ('major', 'Major Finding'), ('critical', 'Critical')], max_length=16)),
                ('description', models.TextField()),
                ('recommended_action', models.TextField(blank=True)),
                ('evidence_files', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('escalated_to_psc', 'Escalated to PSC')], default='open', max_length=24)),
                ('rised_to_rmt', models.BooleanField(default=True)),
                ('rised_to_psc', models.BooleanField(default=True)),
                ('rised_to_super_admin', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('concern_type', models.CharField(choices=[('kpi_issue', 'KPI Issue'), ('gps_issue', 'GPS / Location Issue'), ('verification_issue', 'Field Verification Issue'), ('vendor_behaviour', 'Vendor Behaviour'), ('installation_quality', 'Installation Quality'), ('data_discrepancy', 'Data Discrepancy'), ('other', 'Other')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=16)),
                ('description', models.TextField()),
                ('evidence_files', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('escalated_to_psc', 'Escalated to PSC')], default='open', max_length=24)),
                ('notify_rmt', models.BooleanField(default=True)),
                ('notify_psc', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConcernResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('action_taken', models.CharField(blank=True, max_length=32)),
                ('evidence_files', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='verificationtask',
            name='projects_ver_status_4d7f98_idx',
        ),
        migrations.RenameIndex(
            model_name='anomalyflag',
            new_name='projects_an_install_fc4e81_idx',
            old_name='projects_ano_install_3c0f09_idx',
        ),
        migrations.RenameIndex(
            model_name='anomalyflag',
            new_name='projects_an_project_9cdccf_idx',
            old_name='projects_ano_project_1b0424_idx',
        ),
        migrations.RenameIndex(
            model_name='fieldverification',
            new_name='projects_fi_install_7fb020_idx',
            old_name='projects_fie_install_26a076_idx',
        ),
        migrations.RenameIndex(
            model_name='fieldverification',
            new_name='projects_fi_field_o_0e1086_idx',
            old_name='projects_fie_field_o_06f9f6_idx',
        ),
        migrations.RenameIndex(
            model_name='generatedreport',
            new_name='projects_ge_report__6f85ed_idx',
            old_name='projects_ge_report__4b2ff2_idx',
        ),
        migrations.RenameIndex(
            model_name='generatedreport',
            new_name='projects_ge_generat_ff5322_idx',
            old_name='projects_ge_generat_2bb9b3_idx',
        ),
        migrations.RenameIndex(
            model_name='installationreport',
            new_name='projects_in_gps_lat_c69386_idx',
            old_name='projects_ins_gps_lat_95a4c6_idx',
        ),
        migrations.RenameIndex(
            model_name='installationreport',
            new_name='projects_in_project_66165a_idx',
            old_name='projects_ins_project_9fe959_idx',
        ),
        migrations.RenameIndex(
            model_name='installationreport',
            new_name='projects_in_gis_sta_282a51_idx',
            old_name='projects_ins_gis_sta_32f31d_idx',
        ),
        migrations.RenameIndex(
            model_name='installationreport',
            new_name='projects_in_vendor__059ccc_idx',
            old_name='projects_ins_vendor__50708e_idx',
        ),
        migrations.AlterField(
            model_name='installationreport',
            name='gis_status',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='yellow', max_length=16),
        ),
        migrations.AlterField(
            model_name='installationreport',
            name='prospect_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='paymentclaim',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('RMT Approved', 'RMT Approved'), ('TAC Endorsed', 'TAC Endorsed'), ('PSC Approved', 'PSC Approved'), ('Completed', 'Completed'), ('Held/Audit', 'Held/Audit'), ('Rejected', 'Rejected'), ('Pending', 'Pending (Legacy)'), ('Verified', 'Verified (Legacy)'), ('Approved', 'Approved (Legacy)'), ('Paid', 'Paid (Legacy)')], default='Submitted', max_length=16),
        ),
        migrations.AlterField(
            model_name='project',
            name='prospect_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_low_income_pct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='linked_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_findings', to='projects.paymentclaim'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='linked_installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_findings', to='projects.installationreport'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='linked_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_findings', to='projects.project'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='raised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_findings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concern',
            name='linked_installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concerns', to='projects.installationreport'),
        ),
        migrations.AddField(
            model_name='concern',
            name='linked_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concerns', to='projects.project'),
        ),
        migrations.AddField(
            model_name='concern',
            name='raised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_concerns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concernresponse',
            name='concern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='projects.concern'),
        ),
        migrations.AddField(
            model_name='concernresponse',
            name='responded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['raised_by'], name='projects_au_raised__3c7e51_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['status'], name='projects_au_status_8e2054_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['risk_level'], name='projects_au_risk_le_ad9a56_idx'),
        ),
        migrations.AddIndex(
            model_name='concern',
            index=models.Index(fields=['raised_by'], name='projects_co_raised__3233e8_idx'),
        ),
        migrations.AddIndex(
            model_name='concern',
            index=models.Index(fields=['status'], name='projects_co_status_e236de_idx'),
        ),
        migrations.AddIndex(
            model_name='concern',
            index=models.Index(fields=['severity'], name='projects_co_severit_678e5b_idx'),
        ),
    ]
