# Generated by Django 5.0.6 on 2026-05-01 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_concerns_findings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfinding',
            name='rmt_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='rmt_responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_finding_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='rmt_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='rmt_response_action',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
