# Generated by Django 5.0.6 on 2026-05-01 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auditfinding_rmt_responded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfinding',
            name='psc_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='psc_commented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='psc_commented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_finding_psc_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
