# Generated by Django 5.0.6 on 2026-05-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auditfinding_psc_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentclaim',
            name='district',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
