# Generated by Django 5.0 on 2026-08-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_projectsetup_review_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('setup_pending', 'Setup Pending'), ('setup_under_review', 'Setup Under Review'), ('setup_changes_requested', 'Setup Changes Requested'), ('setup_rejected', 'Setup Rejected'), ('active', 'Active'), ('Pre-Qualification', 'Pre-Qualification'), ('Site-Specific Proposal', 'Site-Specific Proposal'), ('Contracting', 'Contracting'), ('Installation', 'Installation'), ('Field Verification', 'Field Verification'), ('Disbursement', 'Disbursement'), ('Halted', 'Halted'), ('completed', 'Completed'), ('Completed', 'Completed (Legacy)')], max_length=32),
        ),
    ]
