# Generated by Django 5.0.6 on 2026-09-27 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_paid_milestone_reviews(apps, schema_editor):
    # Milestones paid before completion reviews existed are recorded as already
    # decided so existing projects are not blocked waiting for a verification.
    Milestone = apps.get_model('projects', 'Milestone')
    MilestoneCompletionReview = apps.get_model('projects', 'MilestoneCompletionReview')
    reviews = []
    for milestone in Milestone.objects.filter(status__in=['paid', 'Paid']).select_related('project'):
        is_last = not Milestone.objects.filter(
            project_id=milestone.project_id,
            milestone_number__gt=milestone.milestone_number,
        ).exists()
        reviews.append(MilestoneCompletionReview(
            milestone=milestone,
            project_id=milestone.project_id,
            status='decided',
            decision='complete' if is_last else 'proceed',
            verification_notes='Recorded automatically: milestone was paid before completion reviews were introduced.',
            vendor_id=milestone.project.vendor_id,
            vendor_name=milestone.project.vendor_name,
        ))
    MilestoneCompletionReview.objects.bulk_create(reviews)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_milestone_required_installation_pct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('locked', 'Locked'), ('claimable', 'Claimable'), ('claimed', 'Claimed'), ('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('Pending', 'Pending (Legacy)'), ('Submitted', 'Submitted (Legacy)'), ('Verified', 'Verified (Legacy)'), ('Paid', 'Paid (Legacy)')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('setup_pending', 'Setup Pending'), ('setup_under_review', 'Setup Under Review'), ('setup_changes_requested', 'Setup Changes Requested'), ('setup_rejected', 'Setup Rejected'), ('active', 'Active'), ('Pre-Qualification', 'Pre-Qualification'), ('Site-Specific Proposal', 'Site-Specific Proposal'), ('Contracting', 'Contracting'), ('Installation', 'Installation'), ('Field Verification', 'Field Verification'), ('Disbursement', 'Disbursement'), ('Halted', 'Halted'), ('completed', 'Completed'), ('closed', 'Closed'), ('Completed', 'Completed (Legacy)')], max_length=32),
        ),
        migrations.CreateModel(
            name='MilestoneCompletionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('decided', 'Decided')], default='pending', max_length=16)),
                ('decision', models.CharField(blank=True, choices=[('proceed', 'Proceed to Next Milestone'), ('close', 'Close Project'), ('transfer', 'Transfer to Another Vendor'), ('complete', 'Complete Project')], default='', max_length=16)),
                ('verification_notes', models.TextField(blank=True)),
                ('vendor_id', models.CharField(blank=True, max_length=64)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('transferred_to_vendor_id', models.CharField(blank=True, max_length=64)),
                ('transferred_to_vendor_name', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_review', to='projects.milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_reviews', to='projects.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_completion_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(backfill_paid_milestone_reviews, migrations.RunPython.noop),
    ]
