# Generated by Django 5.0.6 on 2026-09-28 10:53

from django.db import migrations, models


def backfill_installation_district(apps, schema_editor):
    from rbf.projects.district_scope import resolve_installation_district

    InstallationReport = apps.get_model('projects', 'InstallationReport')
    reports = InstallationReport.objects.filter(district='').select_related('project', 'project__lot')
    for report in reports.iterator():
        district = resolve_installation_district(report.project, report.gps_lat, report.gps_lng)
        if district:
            InstallationReport.objects.filter(pk=report.pk).update(district=district)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_installationreport_beneficiary_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationreport',
            name='district',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.RunPython(backfill_installation_district, migrations.RunPython.noop),
    ]
