# Generated by Django 5.0.6 on 2026-09-28 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_installationreport_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smartmeterreading',
            name='integrity_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='output_power_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='review_status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], default='accepted', max_length=16),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='source',
            field=models.CharField(choices=[('csv_upload', 'CSV Upload'), ('installation_report', 'Installation Report'), ('api', 'API'), ('legacy', 'Legacy (before provenance tracking)')], default='legacy', max_length=32),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_meter_readings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MeterDataBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('rows_ingested', models.PositiveIntegerField(default=0)),
                ('rows_rejected_on_upload', models.PositiveIntegerField(default=0)),
                ('integrity_findings', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('flagged', 'Flagged'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('correction_requested', 'Correction Requested'), ('superseded', 'Superseded')], default='pending_review', max_length=32)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('correction_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_data_batches', to='projects.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_meter_data_batches', to=settings.AUTH_USER_MODEL)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_data_batches', to='projects.projectdocument')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_data_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='projects.meterdatabatch'),
        ),
        migrations.AddIndex(
            model_name='smartmeterreading',
            index=models.Index(fields=['project', 'meter_id', 'recorded_at'], name='projects_sm_project_412aed_idx'),
        ),
        migrations.AddIndex(
            model_name='meterdatabatch',
            index=models.Index(fields=['project', 'status'], name='projects_me_project_6405d5_idx'),
        ),
    ]
