# Generated by Django 5.0.6 on 2026-10-01 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_meterdatabatch_rejected_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concern',
            name='linked_installation',
        ),
        migrations.RemoveField(
            model_name='concern',
            name='linked_project',
        ),
        migrations.RemoveField(
            model_name='concern',
            name='raised_by',
        ),
        migrations.RemoveField(
            model_name='concernresponse',
            name='concern',
        ),
        migrations.RemoveField(
            model_name='concernresponse',
            name='responded_by',
        ),
        migrations.DeleteModel(
            name='AuditFinding',
        ),
        migrations.DeleteModel(
            name='Concern',
        ),
        migrations.DeleteModel(
            name='ConcernResponse',
        ),
    ]
