# Generated by Django 5.0.6 on 2026-10-01 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_remove_concerns_and_audit_findings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_period', models.CharField(help_text='Reporting month, YYYY-MM.', max_length=7)),
                ('rating', models.CharField(choices=[('on_track', 'On Track'), ('needs_attention', 'Needs Attention'), ('at_risk', 'At Risk')], max_length=24)),
                ('uptime_comment', models.TextField(blank=True)),
                ('beneficiary_comment', models.TextField(blank=True)),
                ('gender_inclusion_comment', models.TextField(blank=True)),
                ('summary', models.TextField()),
                ('recommendations', models.TextField(blank=True)),
                ('kpi_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_reviews', to='projects.project')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-review_period', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteMonitoringVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('system_working', models.BooleanField(blank=True, null=True)),
                ('beneficiary_present', models.BooleanField(blank=True, null=True)),
                ('observations', models.TextField()),
                ('follow_up_action', models.TextField(blank=True)),
                ('follow_up_status', models.CharField(choices=[('none', 'No Follow-up Needed'), ('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='none', max_length=16)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_visits', to='projects.installationreport')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_visits', to='projects.project')),
                ('visited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteMonitoringPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='monitoring_visits/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='projects.sitemonitoringvisit')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='kpireview',
            constraint=models.UniqueConstraint(fields=('project', 'reviewer', 'review_period'), name='unique_kpi_review_per_reviewer_period'),
        ),
        migrations.AddIndex(
            model_name='sitemonitoringvisit',
            index=models.Index(fields=['project', 'visit_date'], name='projects_si_project_e8f2a3_idx'),
        ),
    ]
