# Generated by Django 5.0.6 on 2026-10-03 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_kpireview_sitemonitoringvisit_sitemonitoringphoto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldverification',
            name='verification_round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='verificationtask',
            name='reverification_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='verificationtask',
            name='reverification_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationtask',
            name='reverification_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_reverifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationtask',
            name='verification_round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='verificationtask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paused', 'Paused'), ('Partial', 'Partial'), ('Verified', 'Verified'), ('Flagged', 'Flagged'), ('Terminated', 'Terminated'), ('Reverification Required', 'Reverification Required')], default='Pending', max_length=32),
        ),
        migrations.CreateModel(
            name='OversightReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_role', models.CharField(blank=True, max_length=64)),
                ('subject_type', models.CharField(choices=[('project', 'Project'), ('verification', 'Verification'), ('kpi', 'KPI'), ('vendor', 'Vendor Performance'), ('disbursement', 'Disbursement'), ('monitoring', 'Monitoring')], max_length=16)),
                ('review_status', models.CharField(choices=[('compliant', 'Compliant'), ('delayed', 'Delayed'), ('flagged', 'Flagged'), ('comment', 'Comment'), ('acknowledged', 'Acknowledged'), ('reverification_requested', 'Re-verification Requested')], max_length=32)),
                ('verification_round', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('issue_category', models.CharField(blank=True, max_length=64)),
                ('action_required', models.TextField(blank=True)),
                ('follow_up_status', models.CharField(choices=[('none', 'No Follow-up'), ('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='none', max_length=16)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kpi_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oversight_reviews', to='projects.kpireview')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oversight_reviews', to='projects.milestone')),
                ('monitoring_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oversight_reviews', to='projects.sitemonitoringvisit')),
                ('payment_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oversight_reviews', to='projects.paymentclaim')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oversight_reviews', to='projects.project')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_oversight_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oversight_reviews', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_oversight_reviews', to=settings.AUTH_USER_MODEL)),
                ('verification_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oversight_reviews', to='projects.verificationtask')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject_type', 'review_status'], name='projects_ov_subject_e88857_idx'), models.Index(fields=['follow_up_status'], name='projects_ov_follow__284fea_idx'), models.Index(fields=['reviewer_role'], name='projects_ov_reviewe_8ea406_idx')],
            },
        ),
    ]
