# Generated by Django 5.0.6 on 2026-10-03 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_oversight_reviews_and_reverification'),
        ('tenders', '0058_intenttoawardrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('case_type', models.CharField(choices=[('audit', 'Audit Case'), ('compliance_review', 'Compliance Review')], default='audit', max_length=24)),
                ('audit_area', models.CharField(choices=[('procurement', 'Procurement'), ('vendor', 'Vendor'), ('contract', 'Contract'), ('verification', 'Verification / GPS Evidence'), ('kpi', 'KPI'), ('disbursement', 'Disbursement'), ('system_access', 'System Access'), ('other', 'Other')], max_length=24)),
                ('title', models.CharField(max_length=255)),
                ('scope', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('evidence_collected', 'Evidence Collected'), ('finding_recorded', 'Finding Recorded'), ('management_response', 'Management Response'), ('finalized', 'Audit Finalized'), ('closed', 'Closed')], default='draft', max_length=24)),
                ('criteria', models.TextField(blank=True, help_text='Rule, policy or SRS requirement the records were tested against.')),
                ('finding_type', models.CharField(blank=True, choices=[('compliant', 'No Exception (Compliant)'), ('observation', 'Observation'), ('exception', 'Exception'), ('non_compliance', 'Non-compliance')], max_length=24)),
                ('risk_level', models.CharField(blank=True, choices=[('observation', 'Observation'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], max_length=16)),
                ('finding', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('finding_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('response_requested_at', models.DateTimeField(blank=True, null=True)),
                ('management_response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('corrective_action_owner', models.CharField(blank=True, max_length=255)),
                ('corrective_action_due', models.DateField(blank=True, null=True)),
                ('corrective_action_status', models.CharField(choices=[('not_required', 'Not Required'), ('open', 'Open'), ('in_progress', 'In Progress'), ('implemented', 'Implemented'), ('verified', 'Verified by Auditor')], default='not_required', max_length=16)),
                ('conclusion', models.TextField(blank=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_cases', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_cases', to='tenders.tendercontract')),
                ('payment_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_cases', to='projects.paymentclaim')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_cases', to='projects.project')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_case_responses', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_cases', to='tenders.tender')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_audit_cases', to=settings.AUTH_USER_MODEL)),
                ('verification_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_cases', to='projects.verificationtask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('file', 'File'), ('record', 'Source Record Reference'), ('note', 'Working Note')], max_length=16)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='audit_evidence/')),
                ('source_type', models.CharField(blank=True, max_length=64)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_evidence', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='projects.auditcase')),
            ],
            options={
                'ordering': ['added_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='auditcase',
            index=models.Index(fields=['status'], name='projects_au_status_88ea6f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditcase',
            index=models.Index(fields=['audit_area', 'status'], name='projects_au_audit_a_f39858_idx'),
        ),
        migrations.AddIndex(
            model_name='auditcase',
            index=models.Index(fields=['case_type'], name='projects_au_case_ty_70c3ce_idx'),
        ),
    ]
