# Generated by Django 5.0.6 on 2026-10-04 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_project_archive'),
        ('tenders', '0060_tender_archive_contract_closure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('lifecycle_started_at', models.DateTimeField(blank=True, help_text='Tender creation.', null=True)),
                ('lifecycle_ended_at', models.DateTimeField(blank=True, help_text='Project completion and contract closure.', null=True)),
                ('timeline', models.JSONField(blank=True, default=list)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('dossier', models.FileField(blank=True, null=True, upload_to='project_archives/')),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_archive_records', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_archives', to='tenders.tendercontract')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archives', to='projects.project')),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_archives', to='tenders.tender')),
            ],
            options={
                'ordering': ['-archived_at'],
            },
        ),
    ]
