# Generated by Django 5.0.6 on 2026-10-04 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_project_lifecycle_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='row_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=16),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='generated-reports/%Y/%m/%d/'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['status', 'generated_at'], name='projects_ge_status_8bad60_idx'),
        ),
    ]
