# Generated by Django 5.0.6 on 2026-10-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_report_approval_and_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='format',
            field=models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('excel', 'Excel'), ('geojson', 'GeoJSON'), ('xml', 'IATI XML'), ('zip', 'ZIP package')], max_length=16),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='format',
            field=models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('excel', 'Excel'), ('geojson', 'GeoJSON'), ('xml', 'IATI XML'), ('zip', 'ZIP package')], default='pdf', max_length=16),
        ),
    ]
