# Generated by Django 5.0 on 2026-03-09 00:00
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Evaluation', 'Evaluation'), ('Awarded', 'Awarded'), ('Closed', 'Closed')], default='Draft', max_length=16)),
                ('deadline', models.DateTimeField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('application_type', models.CharField(blank=True, max_length=64)),
                ('stage_type', models.CharField(blank=True, max_length=64)),
                ('procurement_method', models.CharField(blank=True, max_length=64)),
                ('address_for_document', models.CharField(blank=True, max_length=255)),
                ('address_for_security', models.CharField(blank=True, max_length=255)),
                ('place_for_opening', models.CharField(blank=True, max_length=255)),
                ('bidders_eligibility', models.TextField(blank=True)),
                ('time_for_completion', models.CharField(blank=True, max_length=128)),
                ('invited_by', models.CharField(blank=True, max_length=255)),
                ('bidding_currency', models.CharField(blank=True, max_length=64)),
                ('instruction', models.TextField(blank=True)),
                ('last_date_security', models.DateTimeField(blank=True, null=True)),
                ('last_date_submission', models.DateTimeField(blank=True, null=True)),
                ('date_opening', models.DateTimeField(blank=True, null=True)),
                ('pre_tender_meeting_info', models.TextField(blank=True)),
                ('bidders_schedule_purchase', models.BooleanField(default=False)),
                ('tender_security_required', models.BooleanField(default=False)),
                ('contact_details', models.CharField(blank=True, max_length=255)),
                ('technology_types', models.JSONField(blank=True, default=list)),
                ('target_site_type', models.CharField(blank=True, max_length=64)),
                ('is_verified', models.BooleanField(default=False)),
                ('funding_source', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
