# Generated by Django 5.0.6 on 2026-03-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='awarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='awarded_vendor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tender',
            name='awarded_vendor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tender',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
