# Generated by Django 5.0.6 on 2026-03-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_tender_awarded_at_tender_awarded_vendor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='schedule_file',
            field=models.FileField(blank=True, upload_to='tender_schedules/'),
        ),
    ]
