# Generated by Django 5.0.6 on 2026-03-11 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_tender_schedule_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=64)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_email', models.EmailField(blank=True, max_length=254)),
                ('bid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('proposal_file', models.FileField(blank=True, null=True, upload_to='tender_bids/')),
                ('stage', models.CharField(blank=True, max_length=64)),
                ('concept_note', models.TextField(blank=True)),
                ('technical_proposal', models.TextField(blank=True)),
                ('financial_proposal', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Submitted', max_length=32)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='tender',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='tender',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='security_deposit_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tender',
            name='security_deposit_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['status', 'created_at'], name='tenders_ten_status_1dfd5d_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['deadline'], name='tenders_ten_deadlin_585934_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['department'], name='tenders_ten_departm_8a99b9_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['category'], name='tenders_ten_categor_51be61_idx'),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='tenders.tender'),
        ),
        migrations.AddIndex(
            model_name='tenderbid',
            index=models.Index(fields=['tender', 'status'], name='tenders_ten_tender__6401d4_idx'),
        ),
        migrations.AddIndex(
            model_name='tenderbid',
            index=models.Index(fields=['vendor_id'], name='tenders_ten_vendor__3effa5_idx'),
        ),
        migrations.AddIndex(
            model_name='tenderbid',
            index=models.Index(fields=['status'], name='tenders_ten_status_27ae76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenderbid',
            unique_together={('tender', 'vendor_id')},
        ),
    ]
