# Generated by Django 5.0.6 on 2026-03-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_tender_required_documents'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenderbid',
            new_name='tenders_ten_tender__ac55cb_idx',
            old_name='tenders_ten_tender__9fe2b6_idx',
        ),
        migrations.RenameIndex(
            model_name='tenderbidsite',
            new_name='tenders_ten_bid_id_572f0d_idx',
            old_name='tenders_ten_bid_9b8a74_idx',
        ),
        migrations.AddField(
            model_name='tender',
            name='milestone_payment_schedule_file',
            field=models.FileField(blank=True, upload_to='tender_documents/'),
        ),
        migrations.AddField(
            model_name='tender',
            name='rfp_documents_file',
            field=models.FileField(blank=True, upload_to='tender_documents/'),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='boq_file',
            field=models.FileField(blank=True, null=True, upload_to='tender_bids/'),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='financial_proposal_file',
            field=models.FileField(blank=True, null=True, upload_to='tender_bids/'),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='gender_action_plan_file',
            field=models.FileField(blank=True, null=True, upload_to='tender_bids/'),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='implementation_plan_file',
            field=models.FileField(blank=True, null=True, upload_to='tender_bids/'),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='technical_proposal_file',
            field=models.FileField(blank=True, null=True, upload_to='tender_bids/'),
        ),
    ]
