# Generated by Django 5.0.6 on 2026-03-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0008_bid_evaluation_and_contract'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenderbidevaluation',
            new_name='tenders_ten_status_dbc4a8_idx',
            old_name='tenders_ten_status_28d165_idx',
        ),
        migrations.RenameIndex(
            model_name='tenderbidevaluation',
            new_name='tenders_ten_bid_id_4e6b35_idx',
            old_name='tenders_ten_bid_id_79a08d_idx',
        ),
        migrations.RenameIndex(
            model_name='tendercontract',
            new_name='tenders_ten_status_e8bcbd_idx',
            old_name='tenders_ten_status_5686e8_idx',
        ),
        migrations.RenameIndex(
            model_name='tendercontract',
            new_name='tenders_ten_tender__e3314c_idx',
            old_name='tenders_ten_tender__a3a2b2_idx',
        ),
    ]
