# Generated by Django 5.0.6 on 2026-04-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0021_tender_target_districts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderbid',
            name='preferred_district',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='tenderbid',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Revision Required', 'Revision Required'), ('Awarded', 'Awarded'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='tendercontract',
            name='signature_status',
            field=models.CharField(choices=[('awaiting', 'Awaiting'), ('uploaded', 'Uploaded'), ('approved', 'Approved')], default='awaiting', max_length=16),
        ),
    ]
