# Generated by Django 5.0.6 on 2026-04-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0022_add_tenderbid_preferred_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderbid',
            name='technology_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
