# Generated by Django 5.0.6 on 2026-05-02 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0023_add_bid_technology_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('tender', 'Tender'), ('deadline', 'Deadline'), ('award', 'Award'), ('clarification', 'Clarification'), ('training', 'Training'), ('general', 'General')], default='general', max_length=20)),
                ('summary', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('is_pinned', models.BooleanField(default=False)),
                ('show_countdown', models.BooleanField(default=False)),
                ('countdown_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='tenders.tender')),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
            },
        ),
    ]
