# Generated by Django 5.0.6 on 2026-05-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0024_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='approximate_installation_target',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='minimum_service_tier',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
