# Generated by Django 5.0.6 on 2026-05-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0025_tender_approximate_installation_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderbid',
            name='tender_security_file',
            field=models.FileField(blank=True, null=True, upload_to='tender_bids/'),
        ),
    ]
