# Generated by Django 5.0.6 on 2026-05-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0026_add_tender_security_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
