# Generated by Django 5.0.6 on 2026-06-07 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0027_notice_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='dispute_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Evaluation', 'Evaluation'), ('Disputed', 'Disputed'), ('Awarded', 'Awarded'), ('Closed', 'Closed')], default='Draft', max_length=16),
        ),
        migrations.CreateModel(
            name='TenderChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed_by_vendor_id', models.CharField(max_length=64)),
                ('filed_by_vendor_name', models.CharField(max_length=255)),
                ('grounds', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Upheld', 'Upheld'), ('Dismissed', 'Dismissed')], default='Pending', max_length=20)),
                ('filed_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('challenger_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='tenders.tenderbid')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='tenders.tender')),
            ],
            options={
                'ordering': ['-filed_at'],
                'indexes': [models.Index(fields=['tender', 'status'], name='tenders_ten_tender__ba487a_idx')],
            },
        ),
    ]
