# Generated by Django 5.0.6 on 2026-06-13 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0028_tender_dispute_started_at_alter_tender_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='challenge_documents/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('evidence', 'Evidence'), ('legal_argument', 'Legal Argument'), ('correspondence', 'Correspondence'), ('expert_report', 'Expert Report'), ('other', 'Other')], default='evidence', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_confidential', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('actor_role', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='tenderchallenge',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenderchallenge',
            name='assigned_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenderchallenge',
            name='category',
            field=models.CharField(choices=[('procedural', 'Procedural Irregularity'), ('evaluation', 'Evaluation Error'), ('discrimination', 'Discrimination / Bias'), ('conflict_of_interest', 'Conflict of Interest'), ('technical_spec', 'Technical Specification Issue'), ('financial_eval', 'Financial Evaluation Error'), ('eligibility', 'Eligibility / Qualification Error'), ('corruption', 'Corruption / Fraud Allegation'), ('other', 'Other Grounds')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='tenderchallenge',
            name='challenge_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline to file challenge (standstill end)', null=True),
        ),
        migrations.AddField(
            model_name='tenderchallenge',
            name='hearing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenderchallenge',
            name='is_consolidated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenderchallenge',
            name='legal_basis',
            field=models.TextField(blank=True, help_text='Specific legal/regulatory provisions cited'),
        ),
        migrations.AddField(
            model_name='tenderchallenge',
            name='parent_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidated_challenges', to='tenders.tenderchallenge'),
        ),
        migrations.AddField(
            model_name='tenderchallenge',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='tenderchallenge',
            name='requested_relief',
            field=models.TextField(blank=True, help_text='What the challenger wants as remedy'),
        ),
        migrations.AddField(
            model_name='tenderchallenge',
            name='response_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for RMT to respond', null=True),
        ),
        migrations.AddField(
            model_name='tenderchallenge',
            name='review_committee',
            field=models.JSONField(blank=True, default=list, help_text='List of reviewer user IDs'),
        ),
        migrations.AddField(
            model_name='tenderchallenge',
            name='withdrawal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenderchallenge',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Evaluation', 'Evaluation'), ('Standstill', 'Standstill'), ('Disputed', 'Disputed'), ('Awarded', 'Awarded'), ('Closed', 'Closed')], default='Draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='tenderchallenge',
            name='filed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenderchallenge',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenderchallenge',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('additional_info', 'Additional Information Requested'), ('hearing_scheduled', 'Hearing Scheduled'), ('upheld', 'Upheld'), ('partially_upheld', 'Partially Upheld'), ('dismissed', 'Dismissed'), ('withdrawn', 'Withdrawn'), ('settled', 'Settled')], default='draft', max_length=25),
        ),
        migrations.AddIndex(
            model_name='tenderchallenge',
            index=models.Index(fields=['filed_by_vendor_id', 'status'], name='tenders_ten_filed_b_fed131_idx'),
        ),
        migrations.AddIndex(
            model_name='tenderchallenge',
            index=models.Index(fields=['challenge_deadline'], name='tenders_ten_challen_ee3b49_idx'),
        ),
        migrations.AddField(
            model_name='challengedocument',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenders.tenderchallenge'),
        ),
        migrations.AddField(
            model_name='challengedocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challengeevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challengeevent',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tenders.tenderchallenge'),
        ),
    ]
