# Generated by Django 5.0.6 on 2026-08-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0029_add_standstill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='send_email_notification',
            field=models.BooleanField(default=False),
        ),
    ]
