# Generated by Django 5.0 on 2026-08-25 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0030_notice_send_email_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='tenders.tender')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_view_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['tender', 'viewed_at'], name='tenders_ten_tender__6bce74_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tenderviewlog',
            constraint=models.UniqueConstraint(fields=('tender', 'vendor'), name='unique_tender_vendor_view'),
        ),
    ]
