# Generated by Django 5.0.6 on 2026-08-30 07:42

import django.db.models.deletion
from django.db import migrations, models


def backfill_stages_and_deadlines(apps, schema_editor):
    """Backfill existing data into the new 3-stage / workflow model.

    - Every existing tender gets its EOI deadline from its submission deadline.
    - Legacy pre-qualification bids become EOI bids.
    - Legacy unlocked ('site_specific' / stage two) bids become Technical bids with
      the financial stage unlocked, preserving the old combined Stage 2 behaviour.
    """
    Tender = apps.get_model('tenders', 'Tender')
    TenderBid = apps.get_model('tenders', 'TenderBid')
    from django.utils import timezone

    for tender in Tender.objects.all().iterator():
        primary_deadline = tender.last_date_submission or tender.deadline
        if tender.eoi_deadline is None and primary_deadline is not None:
            tender.eoi_deadline = primary_deadline
            tender.save(update_fields=['eoi_deadline'])

    for bid in TenderBid.objects.all().iterator():
        stage_source = str(getattr(bid, 'stage', '') or '').lower()
        stage_type = str(getattr(bid.tender, 'stage_type', '') or '').lower()
        is_stage_two = bid.stage_two_unlocked or 'site' in stage_source or 'detailed' in stage_source
        if is_stage_two:
            bid.bid_stage = 'technical'
            bid.technical_stage_unlocked = True
            bid.technical_stage_unlocked_at = bid.stage_two_unlocked_at or timezone.now()
            bid.technical_stage_source_bid = bid.stage_two_source_bid
            # Preserve legacy combined Stage-2 behaviour: financial unlocked alongside technical.
            bid.financial_stage_unlocked = True
            bid.financial_stage_unlocked_at = bid.technical_stage_unlocked_at or timezone.now()
            bid.save(update_fields=[
                'bid_stage', 'technical_stage_unlocked', 'technical_stage_unlocked_at',
                'technical_stage_source_bid', 'financial_stage_unlocked', 'financial_stage_unlocked_at',
            ])
        else:
            is_pre_qual = (
                'pre' in stage_source
                or 'concept' in stage_source
                or 'stage 1' in stage_source
                or 'pre' in stage_type
                or not bid.stage
            )
            if is_pre_qual:
                bid.bid_stage = 'eoi'
                bid.save(update_fields=['bid_stage'])


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0031_tenderviewlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='eoi_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='financial_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='procurement_workflow',
            field=models.CharField(choices=[('combined', 'Combined'), ('sequential', 'Sequential')], default='sequential', max_length=16),
        ),
        migrations.AddField(
            model_name='tender',
            name='technical_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='bid_stage',
            field=models.CharField(choices=[('eoi', 'EOI'), ('technical', 'Technical'), ('financial', 'Financial'), ('combined', 'Combined')], default='eoi', help_text='Which procurement stage this bid record represents.', max_length=16),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='company_credentials_file',
            field=models.FileField(blank=True, null=True, upload_to='tender_bids/'),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='eoi_narrative',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='financial_sealed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='financial_stage_source_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_stage_drafts', to='tenders.tenderbid'),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='financial_stage_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='financial_stage_unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='financial_standing_file',
            field=models.FileField(blank=True, null=True, upload_to='tender_bids/'),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='financial_standing_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='financial_unsealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='technical_experience_file',
            field=models.FileField(blank=True, null=True, upload_to='tender_bids/'),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='technical_experience_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='technical_stage_source_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_stage_drafts', to='tenders.tenderbid'),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='technical_stage_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='technical_stage_unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='track_record_file',
            field=models.FileField(blank=True, null=True, upload_to='tender_bids/'),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='track_record_summary',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(backfill_stages_and_deadlines, migrations.RunPython.noop),
    ]
