# Generated by Django 5.0.6 on 2026-08-30 12:00

from django.db import migrations


def backfill_staged_deadlines_and_derive_master(apps, schema_editor):
    """Backfill the staged deadlines from the legacy date fields, then derive
    the generic `deadline` master from the staged deadlines before dropping
    the legacy columns."""
    Tender = apps.get_model('tenders', 'Tender')
    for tender in Tender.objects.iterator():
        legacy_deadline = tender.last_date_submission or tender.deadline

        if not tender.eoi_deadline and legacy_deadline:
            tender.eoi_deadline = legacy_deadline

        staged = [v for v in (tender.eoi_deadline, tender.technical_deadline, tender.financial_deadline) if v]
        if staged:
            tender.deadline = max(staged)
        # deadline is NOT NULL; existing rows already carry a value, so leave it
        # untouched when no staged deadlines exist.

        tender.save(update_fields=['eoi_deadline', 'deadline'])


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0032_tender_eoi_deadline_tender_financial_deadline_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_staged_deadlines_and_derive_master, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='tender',
            name='date_opening',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='last_date_security',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='last_date_submission',
        ),
    ]
