# Generated by Django 5.0 on 2026-08-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0033_remove_tender_date_opening_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='publish_approval_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='publish_approval_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='publish_approval_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='publish_approval_reviewed_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tender',
            name='publish_approval_status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_requested', max_length=32),
        ),
        migrations.AlterField(
            model_name='tender',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Publish Approval', 'Pending Publish Approval'), ('Published', 'Published'), ('Evaluation', 'Evaluation'), ('Standstill', 'Standstill'), ('Disputed', 'Disputed'), ('Awarded', 'Awarded'), ('Closed', 'Closed')], default='Draft', max_length=32),
        ),
    ]
