# Generated by Django 5.0 on 2026-08-31 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0034_tender_publish_approval_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderRequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expected_type', models.CharField(blank=True, default='', max_length=64)),
                ('bid_stage', models.CharField(choices=[('eoi', 'EOI'), ('technical', 'Technical'), ('financial', 'Financial'), ('combined', 'Combined')], default='eoi', max_length=32)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='tenders.tender')),
            ],
            options={
                'verbose_name': 'Required Bid Document',
                'verbose_name_plural': 'Required Bid Documents',
                'ordering': ['position', 'id'],
            },
        ),
    ]
