# Generated by Django 5.0 on 2026-08-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0035_tenderrequireddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderbid',
            name='custom_documents',
            field=models.JSONField(blank=True, default=list, help_text='Uploaded custom required bid documents: [{name, expected_type, file_name, file_url}]'),
        ),
    ]
