# Generated by Django 5.0.6 on 2026-08-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0036_tenderbid_custom_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='governing_documents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
