# Generated by Django 5.0 on 2026-09-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0037_tender_governing_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderrequireddocument',
            name='field_key',
            field=models.CharField(blank=True, choices=[('company_credentials_file', 'Company Credentials'), ('financial_standing_file', 'Financial Standing'), ('technical_experience_file', 'Technical Experience'), ('track_record_file', 'Track Record'), ('technical_proposal_file', 'Technical Proposal'), ('boq_file', 'Bill of Quantities'), ('gender_action_plan_file', 'Gender Action Plan'), ('implementation_plan_file', 'Implementation Plan'), ('om_plan_file', 'O&M Plan'), ('reporting_templates_file', 'Reporting Templates'), ('distribution_map_file', 'Distribution Map'), ('financial_proposal_file', 'Financial Proposal'), ('tender_security_file', 'Tender Security')], default='', max_length=64),
        ),
    ]
