# Generated by Django 5.0 on 2026-09-02 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0039_backfill_required_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='max_lots_per_bidder',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TenderLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('technology_types', models.JSONField(blank=True, default=list)),
                ('target_districts', models.JSONField(blank=True, default=list)),
                ('estimated_installation_target', models.PositiveIntegerField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('awarded_vendor_id', models.CharField(blank=True, max_length=64)),
                ('awarded_vendor_name', models.CharField(blank=True, max_length=255)),
                ('intent_to_award_at', models.DateTimeField(blank=True, null=True)),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intent_to_award_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lot_intent_awards', to='tenders.tenderbid')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='tenders.tender')),
            ],
            options={
                'verbose_name': 'Tender Lot',
                'verbose_name_plural': 'Tender Lots',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TenderBidLotOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('subsidy_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_offers', to='tenders.tenderbid')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_offers', to='tenders.tenderlot')),
            ],
            options={
                'ordering': ['lot__position', 'lot_id'],
            },
        ),
        migrations.AddField(
            model_name='tendercontract',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='tenders.tenderlot'),
        ),
        migrations.AddConstraint(
            model_name='tenderbidlotoffer',
            constraint=models.UniqueConstraint(fields=('bid', 'lot'), name='uniq_bid_lot_offer'),
        ),
    ]
