# Generated by Django 5.0.6 on 2026-09-03 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0040_lot_wise_tendering'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderbid',
            name='declared_lots',
            field=models.JSONField(blank=True, default=list, help_text='Lot IDs (as strings) the vendor declared intent to bid on at EOI stage, for lot-wise tenders. Scopes which lots may be tagged to sites and priced in later stages.'),
        ),
        migrations.AddField(
            model_name='tenderbidsite',
            name='lot',
            field=models.ForeignKey(blank=True, help_text='Which lot this site belongs to, for lot-wise tenders. Blank for non-lot-wise tenders.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_sites', to='tenders.tenderlot'),
        ),
    ]
