# Generated by Django 5.0.6 on 2026-09-04 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0041_tenderbid_declared_lots_tenderbidsite_lot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderbidevaluation',
            name='financial_score_auto_calculated',
            field=models.BooleanField(default=False, help_text='True when financial_score was computed from the price formula (100 x lowest bid / this bid) rather than manually typed.'),
        ),
        migrations.AddField(
            model_name='tenderbidevaluation',
            name='stage',
            field=models.CharField(choices=[('technical', 'Technical'), ('financial', 'Financial')], default='technical', max_length=16),
        ),
        migrations.CreateModel(
            name='TenderEvaluationCommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_committee_assignments', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_committee_members', to='tenders.tender')),
            ],
            options={
                'verbose_name': 'Tender Evaluation Committee Member',
                'verbose_name_plural': 'Tender Evaluation Committee Members',
                'ordering': ['assigned_at', 'id'],
                'unique_together': {('tender', 'member')},
            },
        ),
    ]
