# Generated by Django 5.0.6 on 2026-09-04 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0043_backfill_evaluation_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderbidevaluation',
            name='lot',
            field=models.ForeignKey(blank=True, help_text="Set only for a financial-stage row on a lot-wise tender, where a single bid can have a distinct financial score per lot. Technical evaluations stay lot=None — technical merit is shared across a bid's lots.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_evaluations', to='tenders.tenderlot'),
        ),
    ]
