# Generated by Django 5.0.6 on 2026-09-06 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0044_tenderbidevaluation_lot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderInvitedVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_vendors', to='tenders.tender')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tender Invited Vendor',
                'verbose_name_plural': 'Tender Invited Vendors',
                'ordering': ['invited_at', 'id'],
                'unique_together': {('tender', 'vendor')},
            },
        ),
    ]
