# Generated by Django 5.0.6 on 2026-09-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0045_tenderinvitedvendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='currency_rates',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='bid_currency',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
