# Generated by Django 5.0.6 on 2026-09-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0046_tender_currency_rates_tenderbid_bid_currency'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tenderbid',
            name='uniq_tender_vendor_final_bid',
        ),
        migrations.AddConstraint(
            model_name='tenderbid',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['Draft', 'Revision Required', 'Withdrawn', 'Accepted']), _negated=True), fields=('tender', 'vendor_id', 'bid_stage'), name='uniq_tender_vendor_stage_final_bid'),
        ),
    ]
