# Generated by Django 5.0 on 2026-09-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0049_evaluation_integrity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='procurement_workflow',
            field=models.CharField(choices=[('eoi_combined', 'EOI → Combined'), ('combined', 'Combined'), ('sequential', 'Sequential')], default='sequential', max_length=16),
        ),
    ]
