# Generated by Django 5.0.6 on 2026-09-09 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0050_alter_tender_procurement_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='is_eoi_invite_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tender',
            name='linked_eoi_tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_tenders', to='tenders.tender'),
        ),
    ]
