# Generated by Django 5.0.6 on 2026-09-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0051_tender_is_eoi_invite_only_linked_eoi_tender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='advertisement_channels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tender',
            name='bid_validity_period_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='budget_disclosure',
            field=models.CharField(blank=True, choices=[('confidential', 'Confidential'), ('published', 'Published')], max_length=16),
        ),
        migrations.AddField(
            model_name='tender',
            name='clarification_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='digital_signature_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='document_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='document_fee_refundable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tender',
            name='document_fee_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='tender',
            name='language_of_bid_submission',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tender',
            name='max_vendors_to_shortlist',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='minimum_warranty_period_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='site_visit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='submission_method',
            field=models.CharField(choices=[('online_only', 'Online Only'), ('hybrid', 'Hybrid (Online + Physical)')], default='online_only', max_length=16),
        ),
    ]
