# Generated by Django 5.0.6 on 2026-09-13 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0052_tender_procurement_metadata_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderbidlotoffer',
            name='boq_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='TenderBoqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot', models.ForeignKey(blank=True, help_text="Set for a lot-wise tender's per-lot BOQ; blank for a non-lot-wise tender's single BOQ.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boq_template_items', to='tenders.tenderlot')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_template_items', to='tenders.tender')),
            ],
            options={
                'verbose_name': 'Tender BOQ Item',
                'verbose_name_plural': 'Tender BOQ Items',
                'ordering': ['position', 'id'],
            },
        ),
    ]
