# Generated by Django 5.0.6 on 2026-09-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0053_tenderbidlotoffer_boq_items_tenderboqitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='publish_approval_status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], default='not_requested', max_length=32),
        ),
    ]
