# Generated by Django 5.0.6 on 2026-09-16 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0054_alter_tender_publish_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderbidevaluation',
            name='lot',
            field=models.ForeignKey(blank=True, help_text='Scopes an evaluation to a single lot. Lot-wise tenders keep one evaluation per lot per evaluator for BOTH technical and financial stages (a bid covering several lots is scored separately for each). Non-lot-wise tenders leave this NULL.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_evaluations', to='tenders.tenderlot'),
        ),
    ]
