# Generated by Django 5.0.6 on 2026-09-16 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0055_alter_tenderbidevaluation_lot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderAwardRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rationale', models.TextField(blank=True, help_text="Optional note explaining this member's choice.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_recommendations', to='tenders.tenderbid')),
                ('lot', models.ForeignKey(blank=True, help_text='NULL on a non-lot-wise tender (one verdict for the whole tender); set per lot on a lot-wise tender.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='award_recommendations', to='tenders.tenderlot')),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_recommendations', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_recommendations', to='tenders.tender')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tender', 'lot'], name='tenders_ten_tender__dbf2f1_idx'), models.Index(fields=['tender', 'suggested_by'], name='tenders_ten_tender__aa67bc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tenderawardrecommendation',
            constraint=models.UniqueConstraint(condition=models.Q(('lot__isnull', True), _negated=True), fields=('tender', 'lot', 'suggested_by'), name='uniq_recommendation_tender_lot_member'),
        ),
        migrations.AddConstraint(
            model_name='tenderawardrecommendation',
            constraint=models.UniqueConstraint(condition=models.Q(('lot__isnull', True)), fields=('tender', 'suggested_by'), name='uniq_recommendation_tender_member'),
        ),
    ]
