# Generated by Django 5.0.6 on 2026-09-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0056_tenderawardrecommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderlot',
            name='cooling_off_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenderbid',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Revision Required', 'Revision Required'), ('Awarded', 'Awarded'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn'), ('Not Awarded', 'Not Awarded')], default='Draft', max_length=32),
        ),
    ]
