# Generated by Django 5.0 on 2026-09-26 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0057_tenderlot_cooling_off_until_alter_tenderbid_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentToAwardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_vendor_id', models.CharField(blank=True, max_length=64)),
                ('proposed_vendor_name', models.CharField(blank=True, max_length=255)),
                ('ec_agreed_bid_id', models.CharField(blank=True, max_length=64)),
                ('ec_consensus', models.BooleanField(blank=True, null=True)),
                ('ec_override_reason', models.TextField(blank=True)),
                ('send_email', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Super Admin Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested'), ('withdrawn', 'Withdrawn')], default='pending', max_length=32)),
                ('notes', models.TextField(blank=True, help_text="Super Admin's decision notes.")),
                ('requested_by_name', models.CharField(blank=True, max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('from_challenge', models.BooleanField(default=False)),
                ('reviewed_by_name', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('bid', models.ForeignKey(help_text='The bid proposed to receive the intent to award.', on_delete=django.db.models.deletion.CASCADE, related_name='intent_award_requests', to='tenders.tenderbid')),
                ('lot', models.ForeignKey(blank=True, help_text='NULL on a non-lot-wise tender (one approval for the whole award); set per lot on a lot-wise tender.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intent_award_requests', to='tenders.tenderlot')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent_award_requests', to='tenders.tender')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', '-requested_at'], name='tenders_int_status_390714_idx'), models.Index(fields=['tender', 'lot'], name='tenders_int_tender__4178e7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='intenttoawardrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('tender', 'lot'), name='uniq_pending_intent_award_request_per_lot'),
        ),
        migrations.AddConstraint(
            model_name='intenttoawardrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('lot__isnull', True), ('status', 'pending')), fields=('tender',), name='uniq_pending_intent_award_request_whole_tender'),
        ),
    ]
