# Generated by Django 5.0.6 on 2026-10-03 16:54

from django.db import migrations, models

AWARD_STAGE = {'Standstill', 'Disputed', 'Awarded'}


def backfill_lot_status(apps, schema_editor):
    # Same rules as rbf.tenders.lot_status.derive_lot_status. Tender statuses are not changed here.
    TenderLot = apps.get_model('tenders', 'TenderLot')
    for lot in TenderLot.objects.select_related('tender').iterator():
        tender_status = lot.tender.status
        if lot.awarded_at:
            status = 'Awarded'
        elif lot.intent_to_award_bid_id:
            status = 'Disputed' if tender_status == 'Disputed' else 'Standstill'
        elif tender_status in AWARD_STAGE:
            status = 'Evaluation'
        else:
            status = tender_status
        TenderLot.objects.filter(pk=lot.pk).update(status=status)


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0058_intenttoawardrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderlot',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Publish Approval', 'Pending Publish Approval'), ('Published', 'Published'), ('Evaluation', 'Evaluation'), ('Standstill', 'Standstill'), ('Disputed', 'Disputed'), ('Awarded', 'Awarded'), ('Closed', 'Closed')], default='Draft', max_length=32),
        ),
        migrations.RunPython(backfill_lot_status, migrations.RunPython.noop),
    ]
