# Generated by Django 5.0.6 on 2026-10-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0059_tenderlot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tendercontract',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tendercontract',
            name='status',
            field=models.CharField(choices=[('Generated', 'Generated'), ('Submitted', 'Submitted'), ('Signed', 'Signed'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='Generated', max_length=16),
        ),
    ]
