# Generated by Django 5.0.6 on 2026-03-09 09:37

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('RBF Official', 'Rbf Official'), ('TAC Member', 'Tac'), ('DoE Officer', 'Doe Officer'), ('Field Verifier', 'Field Verifier'), ('Vendor', 'Vendor'), ('Digital Admin', 'Admin'), ('UNDP & Donors', 'Undp Donor'), ('Auditor', 'Auditor')], default='Vendor', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
