# Generated by Django 5.0.6 on 2026-03-09 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPrequalification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('organization_type', models.CharField(blank=True, max_length=64)),
                ('tax_id', models.CharField(blank=True, max_length=64)),
                ('hq_address', models.CharField(blank=True, max_length=255)),
                ('technology_types', models.JSONField(blank=True, default=list)),
                ('registration_certificate_name', models.CharField(blank=True, max_length=255)),
                ('tech_tier', models.CharField(blank=True, max_length=32)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('prior_projects', models.PositiveIntegerField(default=0)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('districts_covered', models.PositiveIntegerField(default=0)),
                ('female_beneficiary_target', models.PositiveIntegerField(default=50)),
                ('vulnerable_group_target', models.PositiveIntegerField(default=30)),
                ('declaration_accepted', models.BooleanField(default=False)),
                ('reviewer_comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Clarification Requested', 'Clarification Requested'), ('Rejected', 'Rejected')], default='Pending', max_length=32)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_prequalifications', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prequalifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
