# Generated by Django 5.0.6 on 2026-03-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_registration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprequalification',
            name='authorized_signatory_id',
            field=models.FileField(blank=True, null=True, upload_to='prequalification/signatures/'),
        ),
        migrations.AddField(
            model_name='vendorprequalification',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendorprequalification',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='vendorprequalification',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendorprequalification',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vendorprequalification',
            name='gender_of_focal_person',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=16),
        ),
        migrations.AddField(
            model_name='vendorprequalification',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='prequalification/certificates/'),
        ),
        migrations.AddField(
            model_name='vendorprequalification',
            name='tax_compliance_certificate',
            field=models.FileField(blank=True, null=True, upload_to='prequalification/certificates/'),
        ),
        migrations.AlterField(
            model_name='vendorprequalification',
            name='tech_tier',
            field=models.CharField(blank=True, choices=[('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5')], max_length=32),
        ),
    ]
