# Generated by Django 5.0.6 on 2026-03-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_vendorprequalification_authorized_signatory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprequalification',
            name='experience_financial_proof',
            field=models.FileField(blank=True, null=True, upload_to='prequalification/experience/'),
        ),
        migrations.AddField(
            model_name='vendorprequalification',
            name='trading_license',
            field=models.FileField(blank=True, null=True, upload_to='prequalification/certificates/'),
        ),
    ]
