# Generated by Django 5.0.6 on 2026-04-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_vendorprequalification_bank_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Inactive', 'Inactive'), ('Registered', 'Registered'), ('Suspended', 'Suspended'), ('Blacklisted', 'Blacklisted'), ('Reinstated', 'Reinstated'), ('Requalified', 'Requalified')], default='Active', max_length=16),
        ),
        migrations.AlterField(
            model_name='vendorblacklistcase',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Under Review', 'Under Review'), ('Blacklisted', 'Blacklisted'), ('Rejected', 'Rejected'), ('Expired', 'Expired'), ('Reinstated', 'Reinstated'), ('Requalified', 'Requalified')], default='Initiated', max_length=24),
        ),
    ]
