# Generated by Django 5.0.6 on 2026-05-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_platformconfiguration_national_main_program_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformconfiguration',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='platformconfiguration',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='platformconfiguration',
            name='default_currency',
        ),
        migrations.RemoveField(
            model_name='platformconfiguration',
            name='platform_name',
        ),
        migrations.RemoveField(
            model_name='platformconfiguration',
            name='timezone',
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='default_from_email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='email_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='email_host_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='email_host_user',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='email_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
