# Generated by Django 5.0.6 on 2026-08-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_password_reset_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
