# Generated by Django 5.0.6 on 2026-09-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_rolepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('RBF Management Team', 'RBF Management Team'), ('TAC Member', 'TAC Member'), ('DoE Officer', 'DoE Officer'), ('Field Verifier', 'Field Verifier'), ('Vendor', 'Vendor'), ('Platform Administrator (Super Admin)', 'Platform Administrator (Super Admin)'), ('Project Steering Committee', 'Project Steering Committee'), ('Auditor', 'Auditor'), ('Evaluation Committee', 'Evaluation Committee')], max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('RBF Management Team', 'RBF Management Team'), ('TAC Member', 'TAC Member'), ('DoE Officer', 'DoE Officer'), ('Field Verifier', 'Field Verifier'), ('Vendor', 'Vendor'), ('Platform Administrator (Super Admin)', 'Platform Administrator (Super Admin)'), ('Project Steering Committee', 'Project Steering Committee'), ('Auditor', 'Auditor'), ('Evaluation Committee', 'Evaluation Committee')], default='Vendor', max_length=64),
        ),
    ]
