# Generated by Django 5.0.6 on 2026-09-05 12:05

import rbf.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_rolepermission_role_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfiguration',
            name='financial_scoring_formula',
            field=models.CharField(choices=[('lowest_price_100', 'Lowest price scores 100 (proportional)'), ('linear_deviation_100', 'Linear deviation from lowest price')], default='lowest_price_100', max_length=32),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='technical_scoring_criteria',
            field=models.JSONField(blank=True, default=rbf.users.models.default_technical_scoring_criteria),
        ),
    ]
