# Generated by Django 5.0.6 on 2026-09-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_platformconfiguration_financial_scoring_formula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfiguration',
            name='procurement_methods',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
