# Generated by Django 5.0.6 on 2026-09-14 07:29

import rbf.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_platformconfiguration_procurement_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfiguration',
            name='currencies',
            field=models.JSONField(blank=True, default=rbf.users.models.default_currencies),
        ),
    ]
