# Generated by Django 5.0.6 on 2026-09-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_platformconfiguration_currencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_registration_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='vendor_registration_certificates/'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
