# Generated by Django 5.0.6 on 2026-10-01 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_kpireview_sitemonitoringvisit_sitemonitoringphoto_and_more'),
        ('users', '0029_vendor_registration_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Fraudulent Reporting', 'Fraudulent Reporting'), ('Integrity Breach', 'Integrity Breach'), ('Persistent Non-Performance', 'Persistent Non-Performance'), ('External Legal Action', 'External Legal Action')], max_length=64)),
                ('justification', models.TextField()),
                ('evidence_document', models.FileField(blank=True, null=True, upload_to='blacklisting/recommendations/')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Submitted', max_length=16)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='users.vendorblacklistcase')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist_recommendations', to='projects.project')),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_blacklist_recommendations', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_blacklist_recommendations', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
