# Generated by Django 5.0 on 2026-03-09 00:00
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.CharField(max_length=64)),
                ('recipient_name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Email', 'Email'), ('SMS', 'Sms'), ('In-App', 'In-App')], max_length=16)),
                ('event', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Read', 'Read'), ('Failed', 'Failed')], default='Sent', max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('linked_entity_id', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
