# Generated by Django 5.0.6 on 2026-03-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Email', 'Email'), ('SMS', 'Sms'), ('In-App', 'In App')], max_length=16),
        ),
    ]
