# Generated by Django 5.0.6 on 2026-05-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_reference', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Tender', 'Tender'), ('Deadline', 'Deadline'), ('Award', 'Award'), ('Clarification', 'Clarification'), ('Training', 'Training'), ('General', 'General')], max_length=16)),
                ('linked_tender_id', models.CharField(blank=True, max_length=64, null=True)),
                ('summary', models.TextField(max_length=200)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('send_email_notification', models.BooleanField(default=False)),
                ('show_countdown', models.BooleanField(default=False)),
                ('countdown_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], default='Draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_publish', models.DateTimeField(blank=True, null=True)),
                ('attachments', models.JSONField(default=list)),
                ('created_by', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
