# Generated by Django 5.0.6 on 2026-08-14 13:12

from django.db import migrations, models


def purge_pseudo_recipients(apps, schema_editor):
    Notification = apps.get_model('notifications', 'Notification')
    Notification.objects.filter(recipient_id__in=['rmt', 'psc', 'super_admin']).delete()


def dedupe_notifications(apps, schema_editor):
    from django.db.models import Count

    Notification = apps.get_model('notifications', 'Notification')
    duplicates = (
        Notification.objects.filter(linked_entity_id__gt='')
        .values('recipient_id', 'event', 'linked_entity_id')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )
    for group in duplicates:
        rows = list(
            Notification.objects.filter(
                recipient_id=group['recipient_id'],
                event=group['event'],
                linked_entity_id=group['linked_entity_id'],
            ).order_by('id')
        )
        for row in rows[1:]:
            row.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RunPython(purge_pseudo_recipients, migrations.RunPython.noop),
        migrations.RunPython(dedupe_notifications, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_id', 'status'], name='notificatio_recipie_e285de_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event'], name='notificatio_event_0ebdc5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['timestamp'], name='notificatio_timesta_ccadc8_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('linked_entity_id__gt', '')), fields=('recipient_id', 'event', 'linked_entity_id'), name='uniq_notification_recipient_event_entity'),
        ),
    ]
