# Generated by Django 5.0.6 on 2026-08-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_indexes_and_notice_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='linked_entity_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
