import { Tender, TenderStatus, Project, ProjectStatus, UserRole, Notification, NotificationChannel, NotificationStatus } from "./types";

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "N-001",
    recipientId: "USR-001",
    recipientName: "Admin User",
    type: NotificationChannel.IN_APP,
    event: "Tender Publication",
    title: "New Tender Published",
    body: "Tender RL-2025-SHS-01 has been successfully published and pre-qualified vendors notified.",
    status: NotificationStatus.READ,
    timestamp: "2025-05-10T10:00:00Z",
    linkedEntityId: "T-001",
  },
  {
    id: "N-002",
    recipientId: "V-01",
    recipientName: "SolarLease Ltd",
    type: NotificationChannel.EMAIL,
    event: "Bid Submission",
    title: "Bid Received: RL-2025-SHS-01",
    body: "Your bid for Tender RL-2025-SHS-01 has been received. Reference: BID-9921-X.",
    status: NotificationStatus.DELIVERED,
    timestamp: "2025-05-12T14:30:00Z",
    linkedEntityId: "T-001",
  },
  {
    id: "N-003",
    recipientId: "V-01",
    recipientName: "SolarLease Ltd",
    type: NotificationChannel.SMS,
    event: "Milestone Verified",
    title: "Milestone Approved",
    body: "Milestone M1 for Project P-101 has been verified. Disbursement of 30% initiated.",
    status: NotificationStatus.SENT,
    timestamp: "2025-05-15T09:15:00Z",
    linkedEntityId: "P-101",
  },
  {
    id: "N-004",
    recipientId: "USR-003",
    recipientName: "T. Molapo",
    type: NotificationChannel.IN_APP,
    event: "Field Verification",
    title: "New Survey Submission",
    body: "A new field survey has been submitted for Project P-102. Please review GIS data.",
    status: NotificationStatus.SENT,
    timestamp: "2025-05-16T11:00:00Z",
    linkedEntityId: "P-102",
  },
  {
    id: "N-005",
    recipientId: "PSC-001",
    recipientName: "PSC Chairperson",
    type: NotificationChannel.EMAIL,
    event: "Monthly Briefing",
    title: "Monthly Program Summary - April 2025",
    body: "The monthly summary for Renewable Lesotho is now available. Total output: 850 MWh, Gender Impact: 42%. View full dashboard for details.",
    status: NotificationStatus.DELIVERED,
    timestamp: "2025-05-01T08:00:00Z",
  },
];

export const MOCK_TENDERS: Tender[] = [
  {
    id: "T-001",
    referenceNumber: "RL-2025-SHS-01",
    name: "Solar Home Systems for Thaba-Tseka",
    department: "Department of Energy",
    category: "SHS",
    status: TenderStatus.PUBLISHED,
    deadline: "2025-06-15",
    budget: 500000,
    isVerified: true,
    fundingSource: "Government Budget",
    createdAt: "2025-05-10T08:00:00Z",
    publishedAt: "2025-05-10T08:00:00Z",
  },
  {
    id: "T-002",
    referenceNumber: "RL-2025-MG-04",
    name: "Mini-Grid Development in Qacha's Nek",
    department: "UNDP Lesotho",
    category: "Mini-Grid",
    status: TenderStatus.AWARDED,
    deadline: "2025-05-20",
    budget: 1200000,
    isVerified: true,
    fundingSource: "UNDP Grant",
    awardedAt: "2025-04-28T14:00:00Z",
    awardedVendorName: "SolarLease Ltd",
  },
  {
    id: "T-003",
    referenceNumber: "RL-2025-ICS-02",
    name: "Improved Cookstoves for Rural Households",
    department: "Department of Energy",
    category: "ICS",
    status: TenderStatus.PUBLISHED,
    deadline: "2025-06-30",
    budget: 250000,
    isVerified: true,
    createdAt: "2025-05-14T10:00:00Z",
    publishedAt: "2025-05-14T10:00:00Z",
  },
  {
    id: "T-004",
    referenceNumber: "RL-2025-SWP-01",
    name: "Solar Water Pumping for Agriculture",
    department: "Department of Energy",
    category: "SWP",
    status: TenderStatus.DRAFT,
    deadline: "2025-07-01",
    budget: 450000,
    isVerified: false,
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "P-101",
    vendorId: "V-01",
    vendorName: "SolarLease Ltd",
    techType: "SHS",
    region: "Maseru",
    district: "Maseru",
    projectTitle: "Solar Home Systems for Rural Households",
    status: ProjectStatus.INSTALLATION,
    progress: 65,
    startDate: "2025-01-15",
    endDate: "2025-09-30",
    budget: 180000,
    targetInstallations: 500,
    targetFemalePct: 50,
    targetVulnerablePct: 30,
    targetBeneficiaries: 2200,
    deploymentTeamRoster: "Team Lead: M. Ralejoe; 4 Technicians; 2 Community Mobilizers",
    deploymentEquipmentPlan: "Panels from certified supplier; inverters secured; logistics via Maseru depot.",
    deploymentWorkSchedule: "Phase 1 (Jan-Mar): site prep; Phase 2 (Apr-Jul): installation; Phase 3 (Aug-Sep): QA + commissioning.",
    energyOutput: 4500,
    uptime: 98.5,
    genderImpact: 52,
  },
  {
    id: "P-102",
    vendorId: "V-02",
    vendorName: "EcoGrid Solutions",
    techType: "Mini-Grid",
    region: "Leribe",
    district: "Leribe",
    projectTitle: "Mini-Grid Development in Mokhotlong",
    status: ProjectStatus.VERIFICATION,
    progress: 90,
    startDate: "2024-10-01",
    endDate: "2025-06-15",
    budget: 320000,
    targetInstallations: 3,
    targetFemalePct: 50,
    targetVulnerablePct: 30,
    targetBeneficiaries: 1200,
    deploymentTeamRoster: "Grid Engineer; 6 Technicians; 1 Safety Officer",
    deploymentEquipmentPlan: "Transformers ordered; poles staged; batteries scheduled for June delivery.",
    deploymentWorkSchedule: "Oct-Dec: civil works; Jan-Mar: assembly; Apr-May: commissioning.",
    energyOutput: 12000,
    uptime: 99.2,
    genderImpact: 48,
  },
  {
    id: "P-103",
    vendorId: "V-01",
    vendorName: "SolarLease Ltd",
    techType: "SHS",
    region: "Mafeteng",
    district: "Mafeteng",
    projectTitle: "Solar Home Systems Phase 2",
    status: ProjectStatus.DISBURSEMENT,
    progress: 100,
    startDate: "2024-06-05",
    endDate: "2025-02-20",
    budget: 95000,
    targetInstallations: 200,
    targetFemalePct: 50,
    targetVulnerablePct: 30,
    targetBeneficiaries: 900,
    deploymentTeamRoster: "Completed",
    deploymentEquipmentPlan: "Completed",
    deploymentWorkSchedule: "Completed",
    energyOutput: 3200,
    uptime: 97.8,
    genderImpact: 61,
  },
];

export const ROLES_CONFIG = {
  [UserRole.RBF_OFFICIAL]: {
    permissions: ["all"],
    dashboard: "Macro-level portfolio view",
  },
  [UserRole.UNDP_DONOR]: {
    permissions: ["portfolio_dashboards", "review_disbursements", "review_compliance", "final_disbursement_approval"],
    dashboard: "Oversight & Approval",
  },
  [UserRole.VENDOR]: {
    permissions: ["submit_bid", "view_own_projects", "claim_payment"],
    dashboard: "Performance & Claims",
  },
  [UserRole.DOE_OFFICER]: {
    permissions: ["verify_field", "view_gis"],
    dashboard: "Regional Monitoring",
  },
};
