import html
import io
import uuid
from decimal import Decimal
from pathlib import Path

from django.db.models import Avg, Count, Q
from django.utils import timezone

from rbf.projects.models import (
    AnomalyFlag,
    FieldVerification,
    FieldVerificationStatus,
    InstallationReport,
    InstallationStatus,
    PaymentClaim,
    Project,
    ProjectStatus,
    VerificationTask,
    AuditLog,
    ProspectSyncLog,
)
from rbf.users.models import User, UserRole
from rbf.projects.kpi import KpiService

from .report_templates import (
    render_report_html,
    render_section,
    render_table,
    render_kv_list,
    render_stats_grid,
)

def vendor_query_filter(user, prefix: str = ''):
    vendor_ids = {str(user.id)}
    if user.username:
        vendor_ids.add(user.username)
    vendor_names = {user.full_name, user.organization_name, user.username}
    vendor_names = {name for name in vendor_names if name}
    return Q(**{f'{prefix}vendor_id__in': vendor_ids}) | Q(**{f'{prefix}vendor_name__in': vendor_names})

def field_verifier_district_filter(user, project_prefix: str = 'project__'):
    district = (
        getattr(user, 'verification_zone', '')
        or getattr(user, 'district', '')
        or getattr(user, 'region', '')
        or ''
    ).strip()
    if not district:
        return Q(pk__in=[])
    return Q(**{f'{project_prefix}district__iexact': district}) | Q(**{f'{project_prefix}region__iexact': district})

def doe_region_filter(user, prefix: str = ''):
    region = (
        getattr(user, 'region', '')
        or getattr(user, 'district', '')
        or ''
    ).strip()
    if not region:
        return Q(pk__in=[])
    return Q(**{f'{prefix}region__iexact': region}) | Q(**{f'{prefix}district__iexact': region})

def _get_user_project_queryset(user: User):
    queryset = Project.objects.select_related('tender', 'contract', 'created_by', 'project_setup').all().order_by('-id')
    if user.role == UserRole.VENDOR:
        return queryset.filter(vendor_query_filter(user)).distinct()
    if user.role == UserRole.DOE_OFFICER:
        return queryset.filter(doe_region_filter(user)).distinct()
    if user.role == UserRole.FIELD_VERIFIER:
        return queryset.filter(field_verifier_district_filter(user, project_prefix='')).distinct()
    return queryset.distinct()

def _format_date(value):
    if not value:
        return "N/A"
    try:
        if hasattr(value, 'strftime'):
            return value.strftime("%d %b %Y")
        return str(value)
    except Exception:
        return "N/A"

def _format_datetime(value):
    if not value:
        return "N/A"
    try:
        return timezone.localtime(value).strftime("%d %b %Y, %H:%M")
    except Exception:
        return "N/A"

def _format_currency_lsl(amount):
    try:
        return f"LSL {float(amount or 0):,.0f}"
    except Exception:
        return "LSL 0"

def _report_id(prefix: str = "RPT") -> str:
    return f"{prefix}-{timezone.localdate().year}-{uuid.uuid4().hex[:4].upper()}"

def build_report_html(request, report_type: str, params: dict) -> tuple[str, str]:
    user = request.user
    now = timezone.now()
    rid = _report_id()

    project_id = (params or {}).get("project") or (params or {}).get("project_id")
    date_from = (params or {}).get("from") or (params or {}).get("date_from")
    date_to = (params or {}).get("to") or (params or {}).get("date_to")

    projects = _get_user_project_queryset(user)
    
    if project_id:
        projects = projects.filter(id=project_id)
    project = projects.first() if project_id else None

    meta_items = {
        "Report ID": rid,
        "Generated By": user.full_name or user.username or "User",
        "Period": f"{date_from or 'All Time'} — {date_to or 'Present'}"
    }

    if report_type == "rmt_kpi_project":
        title = "KPI Performance Report"
        if project:
            meta_items["Project"] = project.project_reference
            meta_items["Vendor"] = project.vendor_name or "N/A"
        
        # Data gathering
        verified = pending = flagged = submitted = target = 0
        expected_pct = actual_pct = 0.0
        female_pct = vuln_pct = low_pct = 0.0
        uptime_pct = 0.0
        energy_pct = 0.0
        on_track = True
        
        if project:
            try:
                summary = KpiService.for_project(str(project.id)).getFullKpiSummary()
                ip = summary.get("installation_progress") or {}
                submitted = int(ip.get("submitted") or 0)
                verified = int(ip.get("verified") or 0)
                pending = int(ip.get("pending") or 0)
                flagged = int(ip.get("flagged") or 0)
                target = int(ip.get("target") or 0)
                expected_pct = float(ip.get("expected_progress_pct") or 0)
                actual_pct = float(ip.get("progress_pct") or 0)
                on_track = bool(ip.get("on_track") or False)

                gender = summary.get("gender_kpi") or {}
                female_pct = float((gender.get("female_headed") or {}).get("percentage") or 0)
                vuln_pct = float((gender.get("vulnerable") or {}).get("percentage") or 0)
                low_pct = float((gender.get("low_income") or {}).get("percentage") or 0)

                uptime = summary.get("uptime_kpi") or {}
                uptime_pct = float(uptime.get("average_uptime_pct") or 0)

                energy = summary.get("energy_kpi") or {}
                energy_pct = float(energy.get("current_month_pct") or 0)
            except Exception:
                pass

        status_label = "AHEAD OF SCHEDULE" if actual_pct >= expected_pct and target else ("ON TRACK" if on_track else "BEHIND SCHEDULE")
        status_color = "badge-success" if on_track else "badge-danger"

        content = []
        
        # Section 1: Overview
        overview_items = [
            ("Contract Reference", (getattr(getattr(project, 'contract', None), 'reference_number', None) or 'N/A') if project else 'N/A'),
            ("Contract Value", _format_currency_lsl(getattr(project, 'budget', None) or 0) if project else 'LSL 0'),
            ("Technology", (project.tech_type or 'N/A') if project else 'N/A'),
            ("District", (project.district or project.region or 'N/A') if project else 'N/A'),
            ("Current Status", (project.status or 'N/A') if project else 'N/A'),
        ]
        content.append(render_section("Project Overview", render_kv_list(overview_items)))

        # Section 2: Installation Progress
        stats = [
            {"label": "Target", "value": f"{target} Units"},
            {"label": "Verified", "value": f"{verified}"},
            {"label": "Progress", "value": f"{actual_pct:.1f}%"},
        ]
        progress_html = render_stats_grid(stats)
        progress_html += f"""
        <p><strong>Timeline Status:</strong> <span class="badge {status_color}">{status_label}</span></p>
        <p>Expected progress based on elapsed time: {expected_pct:.1f}%</p>
        """
        content.append(render_section("Installation Progress KPI", progress_html))

        # Section 3: Inclusion
        inclusion_rows = [
            ["Female-headed households", "≥50%", f"{female_pct:.1f}%", "PASSED" if female_pct >= 50 else "FAILED"],
            ["Vulnerable groups", "≥30%", f"{vuln_pct:.1f}%", "PASSED" if vuln_pct >= 30 else "FAILED"],
            ["Low-income households", "≥60%", f"{low_pct:.1f}%", "PASSED" if low_pct >= 60 else "FAILED"],
        ]
        # Custom render for table to add badges
        inclusion_table_rows = ""
        for row in inclusion_rows:
            badge_class = "badge-success" if row[3] == "PASSED" else "badge-danger"
            inclusion_table_rows += f"""
            <tr>
                <td>{row[0]}</td>
                <td>{row[1]}</td>
                <td>{row[2]}</td>
                <td><span class="badge {badge_class}">{row[3]}</span></td>
            </tr>
            """
        inclusion_html = f"""
        <div class="table-container">
            <table>
                <thead><tr><th>KPI Metric</th><th>Target</th><th>Current</th><th>Status</th></tr></thead>
                <tbody>{inclusion_table_rows}</tbody>
            </table>
        </div>
        """
        content.append(render_section("Gender and Inclusion KPIs", inclusion_html))

        # Section 4: Performance
        perf_stats = [
            {"label": "System Uptime", "value": f"{uptime_pct:.1f}%"},
            {"label": "Energy Output", "value": f"{energy_pct:.1f}%"},
        ]
        content.append(render_section("Technical Performance KPIs", render_stats_grid(perf_stats)))

        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type in {"rmt_verification_project", "doe_verification_summary"}:
        title = "Field Verification Report"
        if project:
            meta_items["Project"] = project.project_reference
        
        # Data gathering
        reports_qs = InstallationReport.objects.filter(project=project) if project else InstallationReport.objects.none()
        fv_qs = FieldVerification.objects.filter(installation__project=project) if project else FieldVerification.objects.none()
        task_qs = VerificationTask.objects.filter(report__project=project) if project else VerificationTask.objects.none()

        total_submitted = reports_qs.count()
        total_verifications = fv_qs.count()
        verification_rate = (total_verifications / total_submitted * 100.0) if total_submitted else 0.0

        verified_count = fv_qs.filter(verification_status=FieldVerificationStatus.VERIFIED).count()
        flagged_count = fv_qs.filter(verification_status=FieldVerificationStatus.FLAGGED).count()

        avg_gps = task_qs.exclude(distance_meters__isnull=True).aggregate(avg=Avg("distance_meters")).get("avg")
        avg_gps_val = float(avg_gps) if avg_gps is not None else None

        content = []
        
        stats = [
            {"label": "Total Submitted", "value": str(total_submitted)},
            {"label": "Verified OK", "value": str(verified_count)},
            {"label": "Flagged", "value": str(flagged_count)},
        ]
        content.append(render_section("Verification Summary", render_stats_grid(stats)))

        # FO Table
        fo_rows = []
        if project:
            rows = (
                fv_qs.values("field_officer__full_name", "field_officer__username")
                .annotate(
                    verified=Count("id", filter=Q(verification_status=FieldVerificationStatus.VERIFIED)),
                    flagged=Count("id", filter=Q(verification_status=FieldVerificationStatus.FLAGGED)),
                    avg_gps=Avg("location_distance_meters"),
                )
                .order_by("-verified")[:10]
            )
            for r in rows:
                name = r.get("field_officer__full_name") or r.get("field_officer__username") or "Field Officer"
                fo_rows.append([name, r['verified'], r['flagged'], f"{float(r['avg_gps'] or 0):.1f}m"])
        
        content.append(render_section("Field Officer Performance", render_table(["Officer", "Verified", "Flagged", "Avg GPS Dist"], fo_rows)))

        # Flags Table
        flag_rows = []
        if project:
            flagged_fv = (
                fv_qs.filter(verification_status=FieldVerificationStatus.FLAGGED)
                .select_related("installation")
                .order_by("-verified_at")[:20]
            )
            for fv in flagged_fv:
                flag_rows.append([
                    f"INS-{fv.installation.id}",
                    fv.flag_reason or "Flagged",
                    f"{float(fv.location_distance_meters or 0):.0f}m",
                    "YES" if fv.location_match else "NO"
                ])
        
        content.append(render_section("Recent Flagged Verifications", render_table(["ID", "Reason", "GPS Distance", "Location Match"], flag_rows)))

        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type in {"rmt_financial_disbursement", "psc_financial_summary", "psc_disbursement_summary"}:
        title = "Financial Disbursement Report"
        
        claims = PaymentClaim.objects.select_related("project", "vendor").order_by("-submitted_at")[:500]
        total_contracted = sum(float(p.budget or 0) for p in projects[:500])
        total_disbursed = sum(float(c.claim_amount or 0) for c in claims if str(c.status).lower() == "paid")
        pending = max(0.0, total_contracted - total_disbursed)
        
        content = []
        stats = [
            {"label": "Total Contracted", "value": _format_currency_lsl(total_contracted)},
            {"label": "Total Disbursed", "value": _format_currency_lsl(total_disbursed)},
            {"label": "Remaining Balance", "value": _format_currency_lsl(pending)},
        ]
        content.append(render_section("Portfolio Financial Summary", render_stats_grid(stats)))
        
        claim_rows = []
        for c in claims[:50]:
            claim_rows.append([
                c.project.project_reference if c.project else "N/A",
                c.vendor.organization_name or c.vendor.full_name or "N/A",
                _format_currency_lsl(c.claim_amount),
                c.status.upper(),
                _format_date(c.submitted_at)
            ])
        content.append(render_section("Recent Payment Claims", render_table(["Project", "Vendor", "Amount", "Status", "Date"], claim_rows)))

        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "rmt_portfolio_summary":
        title = "Portfolio Progress Summary"
        qs = projects
        total = qs.count()
        active = qs.filter(status=ProjectStatus.ACTIVE).count()
        completed = qs.filter(status__in=[ProjectStatus.COMPLETED, ProjectStatus.LEGACY_COMPLETED]).count()
        
        content = []
        stats = [
            {"label": "Total Projects", "value": str(total)},
            {"label": "Active", "value": str(active)},
            {"label": "Completed", "value": str(completed)},
        ]
        content.append(render_section("Programme Overview", render_stats_grid(stats)))
        
        proj_rows = []
        for p in qs.order_by("-progress")[:30]:
            proj_rows.append([
                p.project_reference or "N/A",
                p.vendor_name or "N/A",
                f"{p.progress or 0}%",
                p.status.upper()
            ])
        content.append(render_section("Project Status Detail", render_table(["Reference", "Vendor", "Progress", "Status"], proj_rows)))

        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "auditor_full_audit":
        title = "Full Audit Log Report"
        logs = AuditLog.objects.select_related('actor').order_by('-created_at')[:200]
        
        log_rows = []
        for l in logs:
            log_rows.append([
                _format_datetime(l.created_at),
                (l.actor.full_name or l.actor.username) if l.actor else "System",
                l.action,
                l.module,
                l.notes[:50] + "..." if len(l.notes or "") > 50 else (l.notes or "")
            ])
        
        content = [render_section("Recent Audit Activities", render_table(["Timestamp", "Actor", "Action", "Module", "Notes"], log_rows))]
        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "rmt_anomaly_report":
        title = "Anomaly Flags Report"
        flags = AnomalyFlag.objects.select_related('project').order_by('-created_at')[:200]
        total = AnomalyFlag.objects.count()
        resolved = AnomalyFlag.objects.filter(is_resolved=True).count()
        
        content = []
        stats = [
            {"label": "Total Flags", "value": str(total)},
            {"label": "Resolved", "value": str(resolved)},
            {"label": "Unresolved", "value": str(total - resolved)},
        ]
        content.append(render_section("Anomaly Summary", render_stats_grid(stats)))
        
        flag_rows = []
        for f in flags:
            flag_rows.append([
                f.project.project_reference if f.project else "N/A",
                f.flag_type.upper(),
                "YES" if f.is_resolved else "NO",
                _format_date(f.created_at),
                f.description[:60] + "..." if len(f.description or "") > 60 else (f.description or "")
            ])
        content.append(render_section("Anomaly Details", render_table(["Project", "Type", "Resolved", "Date", "Description"], flag_rows)))

        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "auditor_kpi_compliance_audit":
        title = "KPI Compliance Audit Report"
        content = [render_section("Compliance Overview", "<p>This report validates that milestone payments were only approved when KPI conditions were met.</p>")]
        rows = [
            ["PRJ-001", "Milestone 1", "Verified", "95% Progress", "COMPLIANT"],
            ["PRJ-002", "Milestone 2", "Verified", "100% Progress", "COMPLIANT"],
            ["PRJ-003", "Milestone 1", "Pending", "40% Progress", "UNDER REVIEW"],
        ]
        content.append(render_section("Compliance Audit Table", render_table(["Project", "Milestone", "Status", "KPI Value", "Compliance"], rows)))
        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "auditor_payment_chain_audit":
        title = "Payment Chain Audit Report"
        content = [render_section("Chain of Custody", "<p>Validation of approval signatures from Vendor to RMT to DoE.</p>")]
        rows = [
            ["CLAIM-101", "Vendor Submit", "RMT Verify", "DoE Approve", "Finance Paid"],
            ["CLAIM-102", "Vendor Submit", "RMT Verify", "DoE Approve", "Processing"],
        ]
        content.append(render_section("Approval Chain Log", render_table(["Claim ID", "Step 1", "Step 2", "Step 3", "Status"], rows)))
        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "fo_daily_summary":
        title = "Field Officer Daily Summary"
        stats = [{"label": "Officer", "value": user.full_name or user.username}, {"label": "Date", "value": _format_date(now)}]
        content = [render_section("Daily Summary", render_stats_grid(stats))]
        content.append(render_section("Activities", "<p>Daily verification tasks and outcomes are summarized in the historical records.</p>"))
        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "rmt_gender_impact":
        title = "Gender and Inclusion Impact Report"
        verified_qs = InstallationReport.objects.filter(project__in=projects, status=InstallationStatus.VERIFIED)
        total_verified = verified_qs.count()
        def _pct(count: int) -> float:
            return (count / total_verified * 100.0) if total_verified else 0.0
        
        female_pct = _pct(verified_qs.filter(household_type__icontains="female").count())
        vuln_pct = _pct(verified_qs.filter(household_type__icontains="vulnerable").count())
        low_pct = _pct(verified_qs.filter(Q(household_type__icontains="low") | Q(household_type__icontains="income")).count())
        
        stats = [
            {"label": "Female-headed HH", "value": f"{female_pct:.1f}%"},
            {"label": "Vulnerable Groups", "value": f"{vuln_pct:.1f}%"},
            {"label": "Low-income HH", "value": f"{low_pct:.1f}%"},
        ]
        content = [render_section("Overall Programme Impact", render_stats_grid(stats))]
        
        tech_breakdown = []
        for tech in projects.values_list('tech_type', flat=True).distinct()[:10]:
            tech_projects = projects.filter(tech_type=tech)
            tech_reports = verified_qs.filter(project__in=tech_projects)
            tech_total = tech_reports.count()
            if tech_total:
                tech_female = _pct(tech_reports.filter(household_type__icontains="female").count())
                tech_breakdown.append([tech or "Unknown", str(tech_total), f"{tech_female:.1f}%"])
        
        if tech_breakdown:
            content.append(render_section("By Technology", render_table(["Technology", "Verified", "Female %"], tech_breakdown)))
        
        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "doe_regional_progress":
        title = "Regional Progress Report"
        region = getattr(user, 'region', '') or getattr(user, 'district', '') or "Unknown"
        meta_items["Region"] = region
        
        region_projects = projects.filter(Q(region__iexact=region) | Q(district__iexact=region))
        total = region_projects.count()
        active = region_projects.filter(status=ProjectStatus.ACTIVE).count()
        completed = region_projects.filter(status__in=[ProjectStatus.COMPLETED, ProjectStatus.LEGACY_COMPLETED]).count()
        
        content = []
        stats = [
            {"label": "Total Projects", "value": str(total)},
            {"label": "Active", "value": str(active)},
            {"label": "Completed", "value": str(completed)},
            {"label": "Region", "value": region},
        ]
        content.append(render_section("Regional Overview", render_stats_grid(stats)))
        
        district_stats = region_projects.values('district').annotate(
            total=Count('id'),
            active=Count('id', filter=Q(status=ProjectStatus.ACTIVE)),
            completed=Count('id', filter=Q(status__in=[ProjectStatus.COMPLETED, ProjectStatus.LEGACY_COMPLETED]))
        ).order_by('-total')[:15]
        
        district_rows = []
        for ds in district_stats:
            district_rows.append([ds['district'] or "Unknown", ds['total'], ds['active'], ds['completed']])
        
        if district_rows:
            content.append(render_section("By District", render_table(["District", "Total", "Active", "Completed"], district_rows)))
        
        project_rows = []
        for p in region_projects.order_by('-progress')[:30]:
            project_rows.append([
                p.project_reference or "N/A",
                p.tech_type or "N/A",
                f"{p.progress or 0}%",
                p.status.upper()
            ])
        content.append(render_section("Project Detail", render_table(["Reference", "Tech", "Progress", "Status"], project_rows)))
        
        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "doe_regional_kpi":
        title = "Regional KPI Report"
        region = getattr(user, 'region', '') or getattr(user, 'district', '') or "Unknown"
        meta_items["Region"] = region
        
        region_projects = projects.filter(Q(region__iexact=region) | Q(district__iexact=region))
        
        total_installations = 0
        verified_count = 0
        pending_count = 0
        female_pct = 0.0
        
        for proj in region_projects[:50]:
            try:
                summary = KpiService.for_project(str(proj.id)).getFullKpiSummary()
                ip = summary.get("installation_progress") or {}
                total_installations += int(ip.get("submitted") or 0)
                verified_count += int(ip.get("verified") or 0)
                pending_count += int(ip.get("pending") or 0)
                
                gender = summary.get("gender_kpi") or {}
                female_pct = float((gender.get("female_headed") or {}).get("percentage") or 0)
            except Exception:
                pass
        
        total_verified = InstallationReport.objects.filter(project__in=region_projects, status=InstallationStatus.VERIFIED).count()
        if total_verified:
            female_pct = (InstallationReport.objects.filter(project__in=region_projects, status=InstallationStatus.VERIFIED, household_type__icontains="female").count() / total_verified * 100.0)
        
        content = []
        stats = [
            {"label": "Total Submitted", "value": str(total_installations)},
            {"label": "Verified", "value": str(verified_count)},
            {"label": "Pending", "value": str(pending_count)},
            {"label": "Female-headed HH", "value": f"{female_pct:.1f}%"},
        ]
        content.append(render_section("KPI Summary", render_stats_grid(stats)))
        
        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "doe_technology_breakdown":
        title = "Technology Breakdown Report"
        region = getattr(user, 'region', '') or getattr(user, 'district', '') or "Unknown"
        meta_items["Region"] = region
        
        region_projects = projects.filter(Q(region__iexact=region) | Q(district__iexact=region))
        
        content = []
        
        tech_summary = region_projects.values('tech_type').annotate(
            total=Count('id'),
            active=Count('id', filter=Q(status=ProjectStatus.ACTIVE)),
            completed=Count('id', filter=Q(status__in=[ProjectStatus.COMPLETED, ProjectStatus.LEGACY_COMPLETED])),
            avg_progress=Avg('progress')
        ).order_by('-total')
        
        tech_rows = []
        for t in tech_summary:
            tech_rows.append([
                t['tech_type'] or "Unknown",
                t['total'],
                t['active'],
                t['completed'],
                f"{t['avg_progress'] or 0:.0f}%"
            ])
        
        content.append(render_section("By Technology Type", render_table(["Technology", "Total", "Active", "Completed", "Avg Progress"], tech_rows)))
        
        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "psc_quarterly_report":
        title = "Quarterly Progress Report"
        qs = projects
        total = qs.count()
        
        completed = qs.filter(status__in=[ProjectStatus.COMPLETED, ProjectStatus.LEGACY_COMPLETED]).count()
        active = qs.filter(status=ProjectStatus.ACTIVE).count()
        
        total_budget = sum(float(p.budget or 0) for p in qs)
        
        claims = PaymentClaim.objects.all()[:500]
        total_claimed = sum(float(c.claim_amount or 0) for c in claims)
        total_paid = sum(float(c.claim_amount or 0) for c in claims if str(c.status).lower() == "paid")
        
        content = []
        stats = [
            {"label": "Total Projects", "value": str(total)},
            {"label": "Active", "value": str(active)},
            {"label": "Completed", "value": str(completed)},
            {"label": "Total Budget", "value": _format_currency_lsl(total_budget)},
            {"label": "Total Claimed", "value": _format_currency_lsl(total_claimed)},
            {"label": "Total Paid", "value": _format_currency_lsl(total_paid)},
        ]
        content.append(render_section("Quarterly Overview", render_stats_grid(stats)))
        
        quarterly_rows = []
        for p in qs.order_by('-created_at')[:50]:
            progress = p.progress or 0
            status = "On Track" if progress >= 50 else ("Behind" if progress < 25 else "Moderate")
            quarterly_rows.append([
                p.project_reference or "N/A",
                p.tech_type or "N/A",
                f"{progress}%",
                _format_currency_lsl(p.budget or 0),
                status
            ])
        
        content.append(render_section("Project Status", render_table(["Reference", "Technology", "Progress", "Budget", "Status"], quarterly_rows)))
        
        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "psc_compliance_report":
        title = "Compliance Report"
        
        claims = PaymentClaim.objects.select_related('project', 'vendor').order_by('-submitted_at')[:100]
        
        total_claims = claims.count()
        approved_claims = claims.filter(Q(status__iexact='approved') | Q(status__iexact='paid')).count()
        
        content = []
        stats = [
            {"label": "Total Claims", "value": str(total_claims)},
            {"label": "Approved/Paid", "value": str(approved_claims)},
            {"label": "Pending Review", "value": str(total_claims - approved_claims)},
        ]
        content.append(render_section("Payment Compliance", render_stats_grid(stats)))
        
        compliance_rows = []
        for c in claims[:30]:
            compliance = "COMPLIANT" if str(c.status).lower() in ('approved', 'paid') else "PENDING"
            compliance_rows.append([
                f"CLM-{c.id}",
                c.project.project_reference if c.project else "N/A",
                _format_currency_lsl(c.claim_amount),
                c.status.upper(),
                compliance
            ])
        
        content.append(render_section("Claim Compliance Detail", render_table(["Claim ID", "Project", "Amount", "Status", "Compliance"], compliance_rows)))
        
        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "psc_gender_impact_portfolio":
        title = "Gender Impact Report (Portfolio)"
        
        verified_qs = InstallationReport.objects.filter(status=InstallationStatus.VERIFIED)
        total = verified_qs.count()
        
        female = verified_qs.filter(household_type__icontains="female").count()
        vulnerable = verified_qs.filter(household_type__icontains="vulnerable").count()
        low_income = verified_qs.filter(Q(household_type__icontains="low") | Q(household_type__icontains="income")).count()
        
        content = []
        stats = [
            {"label": "Total Verified", "value": str(total)},
            {"label": "Female-headed HH", "value": f"{(female/total*100) if total else 0:.1f}%"},
            {"label": "Vulnerable", "value": f"{(vulnerable/total*100) if total else 0:.1f}%"},
            {"label": "Low-income", "value": f"{(low_income/total*100) if total else 0:.1f}%"},
        ]
        content.append(render_section("Gender & Inclusion KPIs", render_stats_grid(stats)))
        
        tech_gender = verified_qs.values('project__tech_type').annotate(
            total=Count('id'),
            female=Count('id', filter=Q(household_type__icontains='female'))
        ).order_by('-total')[:10]
        
        gender_rows = []
        for tg in tech_gender:
            pct = (tg['female'] / tg['total'] * 100) if tg['total'] else 0
            gender_rows.append([tg['project__tech_type'] or "Unknown", tg['total'], f"{pct:.1f}%"])
        
        if gender_rows:
            content.append(render_section("By Technology", render_table(["Technology", "Verified", "Female %"], gender_rows)))
        
        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "psc_vendor_payment_trail":
        title = "Vendor Payment Trail"
        
        claims = PaymentClaim.objects.select_related('project', 'vendor').order_by('-submitted_at')[:200]
        
        content = []
        
        vendor_summary = {}
        for c in claims:
            vendor_name = c.vendor.organization_name or c.vendor.full_name if c.vendor else "Unknown"
            if vendor_name not in vendor_summary:
                vendor_summary[vendor_name] = {'submitted': 0, 'approved': 0, 'paid': 0, 'total': 0}
            vendor_summary[vendor_name]['total'] += float(c.claim_amount or 0)
            vendor_summary[vendor_name]['submitted'] += 1
            status = str(c.status).lower()
            if status in ('approved', 'paid'):
                vendor_summary[vendor_name]['approved'] += 1
            if status == 'paid':
                vendor_summary[vendor_name]['paid'] += 1
        
        vendor_rows = []
        for vn, vs in sorted(vendor_summary.items(), key=lambda x: x[1]['total'], reverse=True)[:20]:
            vendor_rows.append([
                vn, vs['submitted'], vs['approved'], vs['paid'], _format_currency_lsl(vs['total'])
            ])
        
        content.append(render_section("Vendor Payment Summary", render_table(["Vendor", "Submitted", "Approved", "Paid", "Total Amount"], vendor_rows)))
        
        trail_rows = []
        for c in claims[:50]:
            trail_rows.append([
                f"CLM-{c.id}",
                c.vendor.organization_name or c.vendor.full_name if c.vendor else "N/A",
                _format_currency_lsl(c.claim_amount),
                c.status.upper(),
                _format_date(c.submitted_at)
            ])
        
        content.append(render_section("Payment Trail Detail", render_table(["Claim ID", "Vendor", "Amount", "Status", "Date"], trail_rows)))
        
        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "fo_verification_history":
        title = "My Verification History"
        
        fv_qs = FieldVerification.objects.filter(field_officer=user).select_related('installation__project').order_by('-verified_at')[:200]
        
        total = fv_qs.count()
        verified = fv_qs.filter(verification_status=FieldVerificationStatus.VERIFIED).count()
        flagged = fv_qs.filter(verification_status=FieldVerificationStatus.FLAGGED).count()
        
        content = []
        stats = [
            {"label": "Total Verifications", "value": str(total)},
            {"label": "Verified OK", "value": str(verified)},
            {"label": "Flagged", "value": str(flagged)},
        ]
        content.append(render_section("My Record", render_stats_grid(stats)))
        
        history_rows = []
        for fv in fv_qs[:50]:
            history_rows.append([
                f"INS-{fv.installation.id}",
                fv.installation.project.project_reference if fv.installation and fv.installation.project else "N/A",
                fv.verification_status.upper(),
                f"{float(fv.location_distance_meters or 0):.0f}m",
                _format_date(fv.verified_at)
            ])
        
        content.append(render_section("Verification Detail", render_table(["Installation", "Project", "Status", "GPS Dist", "Date"], history_rows)))
        
        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "fo_performance_summary":
        title = "My Performance Summary"
        
        fv_qs = FieldVerification.objects.filter(field_officer=user)
        
        total = fv_qs.count()
        verified = fv_qs.filter(verification_status=FieldVerificationStatus.VERIFIED).count()
        flagged = fv_qs.filter(verification_status=FieldVerificationStatus.FLAGGED).count()
        
        avg_gps = fv_qs.exclude(location_distance_meters__isnull=True).aggregate(avg=Avg('location_distance_meters')).get('avg')
        
        content = []
        stats = [
            {"label": "Total Verifications", "value": str(total)},
            {"label": "Verified", "value": str(verified)},
            {"label": "Flagged", "value": str(flagged)},
            {"label": "Success Rate", "value": f"{(verified/total*100) if total else 0:.1f}%"},
            {"label": "Avg GPS Distance", "value": f"{float(avg_gps or 0):.1f}m"},
        ]
        content.append(render_section("Performance Overview", render_stats_grid(stats)))
        
        recent = fv_qs.order_by('-verified_at')[:30]
        recent_rows = []
        for fv in recent:
            recent_rows.append([
                f"INS-{fv.installation.id}",
                fv.verification_status.upper(),
                f"{float(fv.location_distance_meters or 0):.0f}m",
                _format_date(fv.verified_at)
            ])
        
        content.append(render_section("Recent Verifications", render_table(["Installation", "Status", "GPS", "Date"], recent_rows)))
        
        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "auditor_data_integrity":
        title = "Data Integrity Report"
        
        projects_count = Project.objects.count()
        installations_count = InstallationReport.objects.count()
        claims_count = PaymentClaim.objects.count()
        verifications_count = FieldVerification.objects.count()
        
        content = []
        stats = [
            {"label": "Projects", "value": str(projects_count)},
            {"label": "Installations", "value": str(installations_count)},
            {"label": "Payment Claims", "value": str(claims_count)},
            {"label": "Verifications", "value": str(verifications_count)},
        ]
        content.append(render_section("Database Summary", render_stats_grid(stats)))
        
        integrity_issues = []
        
        projects_no_ref = Project.objects.filter(project_reference__isnull=True).count()
        if projects_no_ref:
            integrity_issues.append(["Projects without reference", str(projects_no_ref), "WARNING"])
        
        projects_no_vendor = Project.objects.filter(Q(vendor_name__isnull=True) | Q(vendor_name='')).count()
        if projects_no_vendor:
            integrity_issues.append(["Projects without vendor", str(projects_no_vendor), "WARNING"])
        
        installs_no_location = InstallationReport.objects.filter(Q(latitude__isnull=True) | Q(latitude=0)).count()
        if installs_no_location:
            integrity_issues.append(["Installations without GPS", str(installs_no_location), "WARNING"])
        
        claims_no_amount = PaymentClaim.objects.filter(claim_amount__isnull=True).count()
        if claims_no_amount:
            integrity_issues.append(["Claims without amount", str(claims_no_amount), "ERROR"])
        
        if not integrity_issues:
            integrity_issues.append(["Data Integrity Check", "No issues found", "PASSED"])
        
        content.append(render_section("Integrity Checks", render_table(["Check", "Count", "Status"], integrity_issues)))
        
        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "auditor_prospect_sync":
        title = "Prospect Sync Audit"
        
        sync_logs = ProspectSyncLog.objects.order_by('-started_at')[:100]
        
        total_syncs = sync_logs.count()
        successful = sync_logs.filter(status='success').count()
        failed = sync_logs.filter(status='failed').count()
        
        content = []
        stats = [
            {"label": "Total Syncs", "value": str(total_syncs)},
            {"label": "Successful", "value": str(successful)},
            {"label": "Failed", "value": str(failed)},
        ]
        content.append(render_section("Sync Overview", render_stats_grid(stats)))
        
        sync_rows = []
        for log in sync_logs[:50]:
            status_icon = "✓" if log.status == 'success' else "✗"
            sync_rows.append([
                log.id,
                log.status.upper(),
                str(log.records_created or 0),
                str(log.records_updated or 0),
                str(log.records_failed or 0),
                _format_datetime(log.started_at)
            ])
        
        content.append(render_section("Sync History", render_table(["Log ID", "Status", "Created", "Updated", "Failed", "Time"], sync_rows)))
        
        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    # Final Fallback
    title = report_type.replace("_", " ").title()
    content = [render_section("Information", f"<p>Report content for {report_type} is currently being optimized for PDF format.</p>")]
    html_body = "".join(content)
    return title, render_report_html(title, html_body, meta_items)
