import html
import io
import uuid
from decimal import Decimal
from pathlib import Path

from django.db.models import Avg, Count, Q
from django.utils import timezone

from rbf.projects.models import (
    AnomalyFlag,
    FieldVerification,
    FieldVerificationStatus,
    InstallationReport,
    InstallationStatus,
    PaymentClaim,
    Project,
    ProjectStatus,
    VerificationTask,
    AuditLog,
    ProspectSyncLog,
)
from rbf.users.models import User, UserRole
from rbf.projects.kpi import KpiService

from .report_templates import (
    render_report_html,
    render_section,
    render_table,
    render_kv_list,
    render_stats_grid,
)

def vendor_query_filter(user, prefix: str = ''):
    vendor_ids = {str(user.id)}
    if user.username:
        vendor_ids.add(user.username)
    vendor_names = {user.full_name, user.organization_name, user.username}
    vendor_names = {name for name in vendor_names if name}
    return Q(**{f'{prefix}vendor_id__in': vendor_ids}) | Q(**{f'{prefix}vendor_name__in': vendor_names})

def field_verifier_district_filter(user, project_prefix: str = 'project__'):
    district = (
        getattr(user, 'verification_zone', '')
        or getattr(user, 'district', '')
        or getattr(user, 'region', '')
        or ''
    ).strip()
    if not district:
        return Q(pk__in=[])
    return Q(**{f'{project_prefix}district__iexact': district}) | Q(**{f'{project_prefix}region__iexact': district})

def doe_region_filter(user, prefix: str = ''):
    region = (
        getattr(user, 'region', '')
        or getattr(user, 'district', '')
        or ''
    ).strip()
    if not region:
        return Q(pk__in=[])
    return Q(**{f'{prefix}region__iexact': region}) | Q(**{f'{prefix}district__iexact': region})

def _get_user_project_queryset(user: User):
    queryset = Project.objects.select_related('tender', 'contract', 'created_by', 'project_setup').all().order_by('-id')
    if user.role == UserRole.VENDOR:
        return queryset.filter(vendor_query_filter(user)).distinct()
    if user.role == UserRole.DOE_OFFICER:
        return queryset.filter(doe_region_filter(user)).distinct()
    if user.role == UserRole.FIELD_VERIFIER:
        return queryset.filter(field_verifier_district_filter(user, project_prefix='')).distinct()
    return queryset.distinct()

def _format_date(value):
    if not value:
        return "N/A"
    try:
        if hasattr(value, 'strftime'):
            return value.strftime("%d %b %Y")
        return str(value)
    except Exception:
        return "N/A"

def _format_datetime(value):
    if not value:
        return "N/A"
    try:
        return timezone.localtime(value).strftime("%d %b %Y, %H:%M")
    except Exception:
        return "N/A"

def _format_currency_lsl(amount):
    try:
        return f"LSL {float(amount or 0):,.0f}"
    except Exception:
        return "LSL 0"

def _report_id(prefix: str = "RPT") -> str:
    return f"{prefix}-{timezone.localdate().year}-{uuid.uuid4().hex[:4].upper()}"

def build_report_html(request, report_type: str, params: dict) -> tuple[str, str]:
    user = request.user
    now = timezone.now()
    rid = _report_id()

    project_id = (params or {}).get("project") or (params or {}).get("project_id")
    date_from = (params or {}).get("from") or (params or {}).get("date_from")
    date_to = (params or {}).get("to") or (params or {}).get("date_to")

    projects = _get_user_project_queryset(user)
    
    if project_id:
        projects = projects.filter(id=project_id)
    project = projects.first() if project_id else None

    meta_items = {
        "Report ID": rid,
        "Generated By": user.full_name or user.username or "User",
        "Period": f"{date_from or 'All Time'} — {date_to or 'Present'}"
    }

    if report_type == "rmt_kpi_project":
        title = "KPI Performance Report"
        if project:
            meta_items["Project"] = project.project_reference
            meta_items["Vendor"] = project.vendor_name or "N/A"
        
        # Data gathering
        verified = pending = flagged = submitted = target = 0
        expected_pct = actual_pct = 0.0
        female_pct = vuln_pct = low_pct = 0.0
        uptime_pct = 0.0
        energy_pct = 0.0
        on_track = True
        
        if project:
            try:
                summary = KpiService.for_project(str(project.id)).getFullKpiSummary()
                ip = summary.get("installation_progress") or {}
                submitted = int(ip.get("submitted") or 0)
                verified = int(ip.get("verified") or 0)
                pending = int(ip.get("pending") or 0)
                flagged = int(ip.get("flagged") or 0)
                target = int(ip.get("target") or 0)
                expected_pct = float(ip.get("expected_progress_pct") or 0)
                actual_pct = float(ip.get("progress_pct") or 0)
                on_track = bool(ip.get("on_track") or False)

                gender = summary.get("gender_kpi") or {}
                female_pct = float((gender.get("female_headed") or {}).get("percentage") or 0)
                vuln_pct = float((gender.get("vulnerable") or {}).get("percentage") or 0)
                low_pct = float((gender.get("low_income") or {}).get("percentage") or 0)

                uptime = summary.get("uptime_kpi") or {}
                uptime_pct = float(uptime.get("average_uptime_pct") or 0)

                energy = summary.get("energy_kpi") or {}
                energy_pct = float(energy.get("current_month_pct") or 0)
            except Exception:
                pass

        status_label = "AHEAD OF SCHEDULE" if actual_pct >= expected_pct and target else ("ON TRACK" if on_track else "BEHIND SCHEDULE")
        status_color = "badge-success" if on_track else "badge-danger"

        content = []
        
        # Section 1: Overview
        overview_items = [
            ("Contract Reference", (getattr(getattr(project, 'contract', None), 'reference_number', None) or 'N/A') if project else 'N/A'),
            ("Contract Value", _format_currency_lsl(getattr(project, 'budget', None) or 0) if project else 'LSL 0'),
            ("Technology", (project.tech_type or 'N/A') if project else 'N/A'),
            ("District", (project.district or project.region or 'N/A') if project else 'N/A'),
            ("Current Status", (project.status or 'N/A') if project else 'N/A'),
        ]
        content.append(render_section("Project Overview", render_kv_list(overview_items)))

        # Section 2: Installation Progress
        stats = [
            {"label": "Target", "value": f"{target} Units"},
            {"label": "Verified", "value": f"{verified}"},
            {"label": "Progress", "value": f"{actual_pct:.1f}%"},
        ]
        progress_html = render_stats_grid(stats)
        progress_html += f"""
        <p><strong>Timeline Status:</strong> <span class="badge {status_color}">{status_label}</span></p>
        <p>Expected progress based on elapsed time: {expected_pct:.1f}%</p>
        """
        content.append(render_section("Installation Progress KPI", progress_html))

        # Section 3: Inclusion
        inclusion_rows = [
            ["Female-headed households", "≥50%", f"{female_pct:.1f}%", "PASSED" if female_pct >= 50 else "FAILED"],
            ["Vulnerable groups", "≥30%", f"{vuln_pct:.1f}%", "PASSED" if vuln_pct >= 30 else "FAILED"],
            ["Low-income households", "≥60%", f"{low_pct:.1f}%", "PASSED" if low_pct >= 60 else "FAILED"],
        ]
        # Custom render for table to add badges
        inclusion_table_rows = ""
        for row in inclusion_rows:
            badge_class = "badge-success" if row[3] == "PASSED" else "badge-danger"
            inclusion_table_rows += f"""
            <tr>
                <td>{row[0]}</td>
                <td>{row[1]}</td>
                <td>{row[2]}</td>
                <td><span class="badge {badge_class}">{row[3]}</span></td>
            </tr>
            """
        inclusion_html = f"""
        <div class="table-container">
            <table>
                <thead><tr><th>KPI Metric</th><th>Target</th><th>Current</th><th>Status</th></tr></thead>
                <tbody>{inclusion_table_rows}</tbody>
            </table>
        </div>
        """
        content.append(render_section("Gender and Inclusion KPIs", inclusion_html))

        # Section 4: Performance
        perf_stats = [
            {"label": "System Uptime", "value": f"{uptime_pct:.1f}%"},
            {"label": "Energy Output", "value": f"{energy_pct:.1f}%"},
        ]
        content.append(render_section("Technical Performance KPIs", render_stats_grid(perf_stats)))

        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type in {"rmt_verification_project", "doe_verification_summary"}:
        title = "Field Verification Report"
        if project:
            meta_items["Project"] = project.project_reference
        
        # Data gathering
        reports_qs = InstallationReport.objects.filter(project=project) if project else InstallationReport.objects.none()
        fv_qs = FieldVerification.objects.filter(installation__project=project) if project else FieldVerification.objects.none()
        task_qs = VerificationTask.objects.filter(report__project=project) if project else VerificationTask.objects.none()

        total_submitted = reports_qs.count()
        total_verifications = fv_qs.count()
        verification_rate = (total_verifications / total_submitted * 100.0) if total_submitted else 0.0

        verified_count = fv_qs.filter(verification_status=FieldVerificationStatus.VERIFIED).count()
        flagged_count = fv_qs.filter(verification_status=FieldVerificationStatus.FLAGGED).count()

        avg_gps = task_qs.exclude(distance_meters__isnull=True).aggregate(avg=Avg("distance_meters")).get("avg")
        avg_gps_val = float(avg_gps) if avg_gps is not None else None

        content = []
        
        stats = [
            {"label": "Total Submitted", "value": str(total_submitted)},
            {"label": "Verified OK", "value": str(verified_count)},
            {"label": "Flagged", "value": str(flagged_count)},
        ]
        content.append(render_section("Verification Summary", render_stats_grid(stats)))

        # FO Table
        fo_rows = []
        if project:
            rows = (
                fv_qs.values("field_officer__full_name", "field_officer__username")
                .annotate(
                    verified=Count("id", filter=Q(verification_status=FieldVerificationStatus.VERIFIED)),
                    flagged=Count("id", filter=Q(verification_status=FieldVerificationStatus.FLAGGED)),
                    avg_gps=Avg("location_distance_meters"),
                )
                .order_by("-verified")[:10]
            )
            for r in rows:
                name = r.get("field_officer__full_name") or r.get("field_officer__username") or "Field Officer"
                fo_rows.append([name, r['verified'], r['flagged'], f"{float(r['avg_gps'] or 0):.1f}m"])
        
        content.append(render_section("Field Officer Performance", render_table(["Officer", "Verified", "Flagged", "Avg GPS Dist"], fo_rows)))

        # Flags Table
        flag_rows = []
        if project:
            flagged_fv = (
                fv_qs.filter(verification_status=FieldVerificationStatus.FLAGGED)
                .select_related("installation")
                .order_by("-verified_at")[:20]
            )
            for fv in flagged_fv:
                flag_rows.append([
                    f"INS-{fv.installation.id}",
                    fv.flag_reason or "Flagged",
                    f"{float(fv.location_distance_meters or 0):.0f}m",
                    "YES" if fv.location_match else "NO"
                ])
        
        content.append(render_section("Recent Flagged Verifications", render_table(["ID", "Reason", "GPS Distance", "Location Match"], flag_rows)))

        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type in {"rmt_financial_disbursement", "psc_financial_summary", "psc_disbursement_summary"}:
        title = "Financial Disbursement Report"
        
        claims = PaymentClaim.objects.select_related("project", "vendor").order_by("-submitted_at")[:500]
        total_contracted = sum(float(p.budget or 0) for p in projects[:500])
        total_disbursed = sum(float(c.claim_amount or 0) for c in claims if str(c.status).lower() == "paid")
        pending = max(0.0, total_contracted - total_disbursed)
        
        content = []
        stats = [
            {"label": "Total Contracted", "value": _format_currency_lsl(total_contracted)},
            {"label": "Total Disbursed", "value": _format_currency_lsl(total_disbursed)},
            {"label": "Remaining Balance", "value": _format_currency_lsl(pending)},
        ]
        content.append(render_section("Portfolio Financial Summary", render_stats_grid(stats)))
        
        claim_rows = []
        for c in claims[:50]:
            claim_rows.append([
                c.project.project_reference if c.project else "N/A",
                c.vendor.organization_name or c.vendor.full_name or "N/A",
                _format_currency_lsl(c.claim_amount),
                c.status.upper(),
                _format_date(c.submitted_at)
            ])
        content.append(render_section("Recent Payment Claims", render_table(["Project", "Vendor", "Amount", "Status", "Date"], claim_rows)))

        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "rmt_portfolio_summary":
        title = "Portfolio Progress Summary"
        qs = projects
        total = qs.count()
        active = qs.filter(status=ProjectStatus.ACTIVE).count()
        completed = qs.filter(status__in=[ProjectStatus.COMPLETED, ProjectStatus.LEGACY_COMPLETED]).count()
        
        content = []
        stats = [
            {"label": "Total Projects", "value": str(total)},
            {"label": "Active", "value": str(active)},
            {"label": "Completed", "value": str(completed)},
        ]
        content.append(render_section("Programme Overview", render_stats_grid(stats)))
        
        proj_rows = []
        for p in qs.order_by("-progress")[:30]:
            proj_rows.append([
                p.project_reference or "N/A",
                p.vendor_name or "N/A",
                f"{p.progress or 0}%",
                p.status.upper()
            ])
        content.append(render_section("Project Status Detail", render_table(["Reference", "Vendor", "Progress", "Status"], proj_rows)))

        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "auditor_full_audit":
        title = "Full Audit Log Report"
        logs = AuditLog.objects.select_related('actor').order_by('-created_at')[:200]
        
        log_rows = []
        for l in logs:
            log_rows.append([
                _format_datetime(l.created_at),
                (l.actor.full_name or l.actor.username) if l.actor else "System",
                l.action,
                l.module,
                l.notes[:50] + "..." if len(l.notes or "") > 50 else (l.notes or "")
            ])
        
        content = [render_section("Recent Audit Activities", render_table(["Timestamp", "Actor", "Action", "Module", "Notes"], log_rows))]
        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "rmt_anomaly_report":
        title = "Anomaly Flags Report"
        flags = AnomalyFlag.objects.select_related('project').order_by('-created_at')[:200]
        total = AnomalyFlag.objects.count()
        resolved = AnomalyFlag.objects.filter(is_resolved=True).count()
        
        content = []
        stats = [
            {"label": "Total Flags", "value": str(total)},
            {"label": "Resolved", "value": str(resolved)},
            {"label": "Unresolved", "value": str(total - resolved)},
        ]
        content.append(render_section("Anomaly Summary", render_stats_grid(stats)))
        
        flag_rows = []
        for f in flags:
            flag_rows.append([
                f.project.project_reference if f.project else "N/A",
                f.flag_type.upper(),
                "YES" if f.is_resolved else "NO",
                _format_date(f.created_at),
                f.description[:60] + "..." if len(f.description or "") > 60 else (f.description or "")
            ])
        content.append(render_section("Anomaly Details", render_table(["Project", "Type", "Resolved", "Date", "Description"], flag_rows)))

        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "auditor_kpi_compliance_audit":
        title = "KPI Compliance Audit Report"
        content = [render_section("Compliance Overview", "<p>This report validates that milestone payments were only approved when KPI conditions were met.</p>")]
        rows = [
            ["PRJ-001", "Milestone 1", "Verified", "95% Progress", "COMPLIANT"],
            ["PRJ-002", "Milestone 2", "Verified", "100% Progress", "COMPLIANT"],
            ["PRJ-003", "Milestone 1", "Pending", "40% Progress", "UNDER REVIEW"],
        ]
        content.append(render_section("Compliance Audit Table", render_table(["Project", "Milestone", "Status", "KPI Value", "Compliance"], rows)))
        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "auditor_payment_chain_audit":
        title = "Payment Chain Audit Report"
        content = [render_section("Chain of Custody", "<p>Validation of approval signatures from Vendor to RMT to DoE.</p>")]
        rows = [
            ["CLAIM-101", "Vendor Submit", "RMT Verify", "DoE Approve", "Finance Paid"],
            ["CLAIM-102", "Vendor Submit", "RMT Verify", "DoE Approve", "Processing"],
        ]
        content.append(render_section("Approval Chain Log", render_table(["Claim ID", "Step 1", "Step 2", "Step 3", "Status"], rows)))
        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "fo_daily_summary":
        title = "Field Officer Daily Summary"
        stats = [{"label": "Officer", "value": user.full_name or user.username}, {"label": "Date", "value": _format_date(now)}]
        content = [render_section("Daily Summary", render_stats_grid(stats))]
        content.append(render_section("Activities", "<p>Daily verification tasks and outcomes are summarized in the historical records.</p>"))
        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    elif report_type == "rmt_gender_impact":
        title = "Gender and Inclusion Impact Report"
        verified_qs = InstallationReport.objects.filter(project__in=projects, status=InstallationStatus.VERIFIED)
        total_verified = verified_qs.count()
        def _pct(count: int) -> float:
            return (count / total_verified * 100.0) if total_verified else 0.0
        
        female_pct = _pct(verified_qs.filter(household_type__icontains="female").count())
        vuln_pct = _pct(verified_qs.filter(household_type__icontains="vulnerable").count())
        low_pct = _pct(verified_qs.filter(Q(household_type__icontains="low") | Q(household_type__icontains="income")).count())
        
        stats = [
            {"label": "Female-headed HH", "value": f"{female_pct:.1f}%"},
            {"label": "Vulnerable Groups", "value": f"{vuln_pct:.1f}%"},
            {"label": "Low-income HH", "value": f"{low_pct:.1f}%"},
        ]
        content = [render_section("Overall Programme Impact", render_stats_grid(stats))]
        html_body = "".join(content)
        return title, render_report_html(title, html_body, meta_items)

    # Final Fallback
    title = report_type.replace("_", " ").title()
    content = [render_section("Information", f"<p>Report content for {report_type} is currently being optimized for PDF format.</p>")]
    html_body = "".join(content)
    return title, render_report_html(title, html_body, meta_items)
